/* Generated by CIL v. 1.7.2 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct noise1 {
   void *f1 ;
};
struct noise2 {
   void *f1 ;
   void *f2 ;
};
struct inner {
   void *p ;
};
struct outer {
   int a ;
   struct inner x ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
void test1(void) 
{ 
  struct noise2 *s1 ;
  void *tmp ;
  struct noise2 *s2 ;
  void *tmp___0 ;
  struct noise2 *s3 ;
  void *tmp___1 ;

  {
  logComment("Function Entered");
  logBlockEntry("cil-tests1.c", 32);
  tmp = malloc(sizeof(struct noise1 ));
  logAssignNoOffset("cil-tests1.c", 32, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct noise1 )", sizeof(struct noise1 ));
  s1 = (struct noise2 *)((struct noise1 *)tmp);
  logAssignNoOffset("cil-tests1.c", 32, & s1, "struct noise2 *", "s1", s1, "struct noise2",
                    "(struct noise2 *)((struct noise1 *)tmp)", 0);
  tmp___0 = malloc(sizeof(struct noise1 ));
  logAssignNoOffset("cil-tests1.c", 33, & tmp___0, "void *", "tmp___0", tmp___0, "void",
                    "malloc", 1);
  logMallocInfo("sizeof(struct noise1 )", sizeof(struct noise1 ));
  s2 = (struct noise2 *)((struct noise1 *)tmp___0);
  logAssignNoOffset("cil-tests1.c", 33, & s2, "struct noise2 *", "s2", s2, "struct noise2",
                    "(struct noise2 *)((struct noise1 *)tmp___0)", 0);
  tmp___1 = malloc(sizeof(struct noise1 ));
  logAssignNoOffset("cil-tests1.c", 34, & tmp___1, "void *", "tmp___1", tmp___1, "void",
                    "malloc", 1);
  logMallocInfo("sizeof(struct noise1 )", sizeof(struct noise1 ));
  s3 = (struct noise2 *)((struct noise1 *)tmp___1);
  logAssignNoOffset("cil-tests1.c", 34, & s3, "struct noise2 *", "s3", s3, "struct noise2",
                    "(struct noise2 *)((struct noise1 *)tmp___1)", 0);
  s1->f2 = (void *)s2;
  logAssignOffset("cil-tests1.c", 35, s1, "struct noise2", "*s1", & s1->f2, "void *",
                  "s1->f2", s1->f2, "void", "(void *)s2", 0);
  s2->f2 = (void *)s3;
  logAssignOffset("cil-tests1.c", 36, s2, "struct noise2", "*s2", & s2->f2, "void *",
                  "s2->f2", s2->f2, "void", "(void *)s3", 0);
  s3->f2 = (void *)s1;
  logAssignOffset("cil-tests1.c", 37, s3, "struct noise2", "*s3", & s3->f2, "void *",
                  "s3->f2", s3->f2, "void", "(void *)s1", 0);
  logFree("cil-tests1.c", 38, "(void *)s1", (void *)s1);
  free((void *)s1);
  logFree("cil-tests1.c", 39, "(void *)s2", (void *)s2);
  free((void *)s2);
  logFree("cil-tests1.c", 40, "(void *)s3", (void *)s3);
  free((void *)s3);
  logBlockExit("cil-tests1.c", 40);
  {
  logVarOutOfScope("s1", & s1);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("s2", & s2);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("s3", & s3);
  logVarOutOfScope("tmp___1", & tmp___1);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void test2(void) 
{ 
  struct noise1 s1 ;

  {
  logComment("Function Entered");
  logBlockEntry("cil-tests1.c", 45);
  s1.f1 = (void *)(& s1);
  logAssignOffset("cil-tests1.c", 45, & s1, "struct noise1", "s1", & s1.f1, "void *",
                  "s1.f1", s1.f1, "void", "(void *)(& s1)", 0);
  logBlockExit("cil-tests1.c", 45);
  {
  logVarOutOfScope("s1", & s1);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void test3(void) 
{ 
  struct outer s1 ;

  {
  logComment("Function Entered");
  logBlockEntry("cil-tests1.c", 50);
  s1.x.p = (void *)0;
  logAssignOffset("cil-tests1.c", 50, & s1, "struct outer", "s1", & s1.x.p, "void *",
                  "s1.x.p", s1.x.p, "void", "(void *)0", 0);
  logBlockExit("cil-tests1.c", 50);
  {
  logVarOutOfScope("s1", & s1);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(int argc , char **argv ) 
{ 


  {
  logComment("Function Entered");
  test1();
  test2();
  test3();
  {
  logVarOutOfScope("argv", & argv);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
