/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct binary_tree {
   int payload ;
   struct binary_tree *left ;
   struct binary_tree *right ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
void insert(struct binary_tree *root , struct binary_tree *element ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "root", "struct binary_tree *", & root);
  logVarInScope("formal", "element", "struct binary_tree *", & element);
  if (element->payload < root->payload) {
    if ((unsigned long )root->left != (unsigned long )((void *)0)) {
      insert(root->left, element);
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    } else {
      logBlockEntry("binary-tree.c", 17);
      root->left = element;
      logAssignOffset("binary-tree.c", 17, root, "struct binary_tree", "*root", & root->left,
                      "struct binary_tree *", "root->left", root->left, "struct binary_tree",
                      "element", 0);
      logBlockExit("binary-tree.c", 17);
    }
  } else
  if (element->payload > root->payload) {
    if ((unsigned long )root->right != (unsigned long )((void *)0)) {
      insert(root->right, element);
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    } else {
      logBlockEntry("binary-tree.c", 23);
      root->right = element;
      logAssignOffset("binary-tree.c", 23, root, "struct binary_tree", "*root", & root->right,
                      "struct binary_tree *", "root->right", root->right, "struct binary_tree",
                      "element", 0);
      logBlockExit("binary-tree.c", 23);
    }
  }
  {
  logVarOutOfScope("root", & root);
  logVarOutOfScope("element", & element);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void print_tree(struct binary_tree *root ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "root", "struct binary_tree *", & root);
  if ((unsigned long )root->left != (unsigned long )((void *)0)) {
    printf((char const   * __restrict  )"[l]");
    print_tree(root->left);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  printf((char const   * __restrict  )"%d\n", root->payload);
  if ((unsigned long )root->right != (unsigned long )((void *)0)) {
    printf((char const   * __restrict  )"[r]");
    print_tree(root->right);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("root", & root);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(int argc , char **argv ) 
{ 
  int payload[14] ;
  int root_payload ;
  int payload_len ;
  struct binary_tree *root ;
  struct binary_tree *elem_tmp ;
  void *tmp ;
  struct binary_tree *tmp___0 ;
  int i ;
  void *tmp___1 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "root", "struct binary_tree *", & root);
  logVarInScope("local", "elem_tmp", "struct binary_tree *", & elem_tmp);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "tmp___0", "struct binary_tree *", & tmp___0);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logBlockEntry("binary-tree.c", 42);
  payload[0] = 20;
  payload[1] = 10;
  payload[2] = 5;
  payload[3] = 15;
  payload[4] = 30;
  payload[5] = 25;
  payload[6] = 35;
  payload[7] = 60;
  payload[8] = 50;
  payload[9] = 45;
  payload[10] = 55;
  payload[11] = 70;
  payload[12] = 65;
  payload[13] = 75;
  root_payload = 40;
  payload_len = 14;
  tmp = malloc(sizeof(*root));
  logAssignNoOffset("binary-tree.c", 48, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(*root)", sizeof(*root));
  root = (struct binary_tree *)tmp;
  logAssignNoOffset("binary-tree.c", 48, & root, "struct binary_tree *", "root", root,
                    "struct binary_tree", "(struct binary_tree *)tmp", 0);
  tmp___0 = (struct binary_tree *)((void *)0);
  logAssignNoOffset("binary-tree.c", 49, & tmp___0, "struct binary_tree *", "tmp___0",
                    tmp___0, "struct binary_tree", "(struct binary_tree *)((void *)0)",
                    0);
  root->right = tmp___0;
  logAssignOffset("binary-tree.c", 49, root, "struct binary_tree", "*root", & root->right,
                  "struct binary_tree *", "root->right", root->right, "struct binary_tree",
                  "tmp___0", 0);
  root->left = tmp___0;
  logAssignOffset("binary-tree.c", 49, root, "struct binary_tree", "*root", & root->left,
                  "struct binary_tree *", "root->left", root->left, "struct binary_tree",
                  "tmp___0", 0);
  root->payload = root_payload;
  i = 0;
  logBlockExit("binary-tree.c", 52);
  while (i < payload_len) {
    logComment("Loop-iteration-start_binary-tree.c_52");
    {
    logBlockEntry("binary-tree.c", 53);
    tmp___1 = malloc(sizeof(*elem_tmp));
    logAssignNoOffset("binary-tree.c", 53, & tmp___1, "void *", "tmp___1", tmp___1,
                      "void", "malloc", 1);
    logMallocInfo("sizeof(*elem_tmp)", sizeof(*elem_tmp));
    elem_tmp = (struct binary_tree *)tmp___1;
    logAssignNoOffset("binary-tree.c", 53, & elem_tmp, "struct binary_tree *", "elem_tmp",
                      elem_tmp, "struct binary_tree", "(struct binary_tree *)tmp___1",
                      0);
    elem_tmp->payload = payload[i];
    logBlockExit("binary-tree.c", 55);
    insert(root, elem_tmp);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    i ++;
    logBlockExit("binary-tree.c", 52);
    }
    logComment("Loop-iteration-end");
  }
  print_tree(root);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("root", & root);
  logVarOutOfScope("elem_tmp", & elem_tmp);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("tmp___1", & tmp___1);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
