/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct dll_node {
   struct dll_node *next ;
   struct dll_node *prev ;
};
struct skip_node {
   struct dll_node *payload ;
   struct skip_node *next ;
   struct skip_node *down ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
struct skip_node *create_lvl(int lvl_length ) 
{ 
  struct skip_node *tmp1 ;
  struct skip_node *tmp2 ;
  struct skip_node *lvl ;
  void *tmp ;
  int i ;
  void *tmp___0 ;

  {
  logComment("Function Entered");
  logVarInScope("local", "tmp1", "struct skip_node *", & tmp1);
  logVarInScope("local", "tmp2", "struct skip_node *", & tmp2);
  logVarInScope("local", "lvl", "struct skip_node *", & lvl);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logBlockEntry("mbg-skip-with-dll-children.c", 30);
  lvl = (struct skip_node *)((void *)0);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 30, & lvl, "struct skip_node *",
                    "lvl", lvl, "struct skip_node", "(struct skip_node *)((void *)0)",
                    0);
  tmp2 = (struct skip_node *)((void *)0);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 31, & tmp2, "struct skip_node *",
                    "tmp2", tmp2, "struct skip_node", "(struct skip_node *)((void *)0)",
                    0);
  tmp1 = tmp2;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 31, & tmp1, "struct skip_node *",
                    "tmp1", tmp1, "struct skip_node", "tmp2", 0);
  logBlockExit("mbg-skip-with-dll-children.c", 31);
  if (lvl_length >= 1) {
    logBlockEntry("mbg-skip-with-dll-children.c", 34);
    tmp = malloc(sizeof(*lvl));
    logAssignNoOffset("mbg-skip-with-dll-children.c", 34, & tmp, "void *", "tmp",
                      tmp, "void", "malloc", 1);
    logMallocInfo("sizeof(*lvl)", sizeof(*lvl));
    lvl = (struct skip_node *)tmp;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 34, & lvl, "struct skip_node *",
                      "lvl", lvl, "struct skip_node", "(struct skip_node *)tmp", 0);
    logBlockExit("mbg-skip-with-dll-children.c", 34);
    if (! lvl) {
      exit(1);
    }
    logBlockEntry("mbg-skip-with-dll-children.c", 38);
    tmp1 = lvl;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 38, & tmp1, "struct skip_node *",
                      "tmp1", tmp1, "struct skip_node", "lvl", 0);
    i = 1;
    logBlockExit("mbg-skip-with-dll-children.c", 39);
    while (i < lvl_length) {
      logComment("Loop-iteration-start_mbg-skip-with-dll-children.c_39");
      {
      logBlockEntry("mbg-skip-with-dll-children.c", 40);
      tmp___0 = malloc(sizeof(*tmp2));
      logAssignNoOffset("mbg-skip-with-dll-children.c", 40, & tmp___0, "void *", "tmp___0",
                        tmp___0, "void", "malloc", 1);
      logMallocInfo("sizeof(*tmp2)", sizeof(*tmp2));
      tmp2 = (struct skip_node *)tmp___0;
      logAssignNoOffset("mbg-skip-with-dll-children.c", 40, & tmp2, "struct skip_node *",
                        "tmp2", tmp2, "struct skip_node", "(struct skip_node *)tmp___0",
                        0);
      logBlockExit("mbg-skip-with-dll-children.c", 40);
      if (! tmp2) {
        exit(1);
      }
      logBlockEntry("mbg-skip-with-dll-children.c", 42);
      tmp1->next = tmp2;
      logAssignOffset("mbg-skip-with-dll-children.c", 42, tmp1, "struct skip_node",
                      "*tmp1", & tmp1->next, "struct skip_node *", "tmp1->next", tmp1->next,
                      "struct skip_node", "tmp2", 0);
      tmp1 = tmp2;
      logAssignNoOffset("mbg-skip-with-dll-children.c", 43, & tmp1, "struct skip_node *",
                        "tmp1", tmp1, "struct skip_node", "tmp2", 0);
      i ++;
      logBlockExit("mbg-skip-with-dll-children.c", 39);
      }
      logComment("Loop-iteration-end");
    }
  }
  {
  logVarOutOfScope("tmp1", & tmp1);
  logVarOutOfScope("tmp2", & tmp2);
  logVarOutOfScope("lvl", & lvl);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  {
  logComment("Function Exited");
  return (lvl);
  }
  }
}
}
int conn_lvl1_to_lvl2[2]  = {      0,      2};
int conn_lvl2_to_lvl3[3]  = {      0,      2,      3};
struct skip_node *forward_to_item(struct skip_node *lvl , int item ) 
{ 
  struct skip_node *iter ;
  int i ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "lvl", "struct skip_node *", & lvl);
  logVarInScope("local", "iter", "struct skip_node *", & iter);
  logBlockEntry("mbg-skip-with-dll-children.c", 55);
  iter = lvl;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 55, & iter, "struct skip_node *",
                    "iter", iter, "struct skip_node", "lvl", 0);
  i = 0;
  logBlockExit("mbg-skip-with-dll-children.c", 56);
  while (i < item) {
    logComment("Loop-iteration-start_mbg-skip-with-dll-children.c_56");
    {
    logBlockEntry("mbg-skip-with-dll-children.c", 57);
    iter = iter->next;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 57, & iter, "struct skip_node *",
                      "iter", iter, "struct skip_node", "iter->next", 0);
    i ++;
    logBlockExit("mbg-skip-with-dll-children.c", 56);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("lvl", & lvl);
  logVarOutOfScope("iter", & iter);
  {
  logComment("Function Exited");
  return (iter);
  }
  }
}
}
void conn_two_lvls(struct skip_node *first , struct skip_node *second , int *conns ,
                   int length ) 
{ 
  struct skip_node *sk_link_first ;
  struct skip_node *sk_link_second ;
  int i ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "first", "struct skip_node *", & first);
  logVarInScope("formal", "second", "struct skip_node *", & second);
  logVarInScope("formal", "conns", "int *", & conns);
  logVarInScope("local", "sk_link_first", "struct skip_node *", & sk_link_first);
  logVarInScope("local", "sk_link_second", "struct skip_node *", & sk_link_second);
  logBlockEntry("mbg-skip-with-dll-children.c", 62);
  sk_link_first = first;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 62, & sk_link_first, "struct skip_node *",
                    "sk_link_first", sk_link_first, "struct skip_node", "first", 0);
  sk_link_second = (struct skip_node *)((void *)0);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 63, & sk_link_second, "struct skip_node *",
                    "sk_link_second", sk_link_second, "struct skip_node", "(struct skip_node *)((void *)0)",
                    0);
  i = 0;
  logBlockExit("mbg-skip-with-dll-children.c", 64);
  while (i < length) {
    logComment("Loop-iteration-start_mbg-skip-with-dll-children.c_64");
    {
    printf((char const   * __restrict  )"\tConnecting first index %d to second index %d\n",
           i, *(conns + i));
    sk_link_second = forward_to_item(second, *(conns + i));
    logBlockEntry("mbg-skip-with-dll-children.c", 66);
    logAssignNoOffset("mbg-skip-with-dll-children.c", 66, & sk_link_second, "struct skip_node *",
                      "sk_link_second", sk_link_second, "struct skip_node", "forward_to_item",
                      0);
    dumpVarsOutOfScope();
    logBlockExit("mbg-skip-with-dll-children.c", 67);
    printf((char const   * __restrict  )"\tforwarding done\n");
    logBlockEntry("mbg-skip-with-dll-children.c", 68);
    sk_link_first->down = sk_link_second;
    logAssignOffset("mbg-skip-with-dll-children.c", 68, sk_link_first, "struct skip_node",
                    "*sk_link_first", & sk_link_first->down, "struct skip_node *",
                    "sk_link_first->down", sk_link_first->down, "struct skip_node",
                    "sk_link_second", 0);
    sk_link_first = sk_link_first->next;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 69, & sk_link_first, "struct skip_node *",
                      "sk_link_first", sk_link_first, "struct skip_node", "sk_link_first->next",
                      0);
    i ++;
    logBlockExit("mbg-skip-with-dll-children.c", 64);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("first", & first);
  logVarOutOfScope("second", & second);
  logVarOutOfScope("conns", & conns);
  logVarOutOfScope("sk_link_first", & sk_link_first);
  logVarOutOfScope("sk_link_second", & sk_link_second);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void create_dll(struct dll_node *first , int items ) 
{ 
  struct dll_node *tmp ;
  int i ;
  void *tmp___0 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "first", "struct dll_node *", & first);
  logVarInScope("local", "tmp", "struct dll_node *", & tmp);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  i = 0;
  while (i < items) {
    logComment("Loop-iteration-start_mbg-skip-with-dll-children.c_75");
    {
    logBlockEntry("mbg-skip-with-dll-children.c", 76);
    tmp___0 = malloc(sizeof(*tmp));
    logAssignNoOffset("mbg-skip-with-dll-children.c", 76, & tmp___0, "void *", "tmp___0",
                      tmp___0, "void", "malloc", 1);
    logMallocInfo("sizeof(*tmp)", sizeof(*tmp));
    tmp = (struct dll_node *)tmp___0;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 76, & tmp, "struct dll_node *",
                      "tmp", tmp, "struct dll_node", "(struct dll_node *)tmp___0",
                      0);
    first->next = tmp;
    logAssignOffset("mbg-skip-with-dll-children.c", 77, first, "struct dll_node",
                    "*first", & first->next, "struct dll_node *", "first->next", first->next,
                    "struct dll_node", "tmp", 0);
    tmp->prev = first;
    logAssignOffset("mbg-skip-with-dll-children.c", 78, tmp, "struct dll_node", "*tmp",
                    & tmp->prev, "struct dll_node *", "tmp->prev", tmp->prev, "struct dll_node",
                    "first", 0);
    tmp->next = (struct dll_node *)((void *)0);
    logAssignOffset("mbg-skip-with-dll-children.c", 79, tmp, "struct dll_node", "*tmp",
                    & tmp->next, "struct dll_node *", "tmp->next", tmp->next, "struct dll_node",
                    "(struct dll_node *)((void *)0)", 0);
    first = tmp;
    logAssignNoOffset("mbg-skip-with-dll-children.c", 80, & first, "struct dll_node *",
                      "first", first, "struct dll_node", "tmp", 0);
    i ++;
    logBlockExit("mbg-skip-with-dll-children.c", 75);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("first", & first);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(int argc , char **argv ) 
{ 
  struct skip_node *sk_ep ;
  struct skip_node *lvl ;
  struct skip_node *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "sk_ep", "struct skip_node *", & sk_ep);
  logVarInScope("local", "lvl", "struct skip_node *", & lvl);
  logVarInScope("local", "tmp", "struct skip_node *", & tmp);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logVarInScope("local", "tmp___2", "void *", & tmp___2);
  printf((char const   * __restrict  )"Create first level with length %d\n", 2);
  sk_ep = create_lvl(2);
  logBlockEntry("mbg-skip-with-dll-children.c", 91);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 91, & sk_ep, "struct skip_node *",
                    "sk_ep", sk_ep, "struct skip_node", "create_lvl", 0);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 92);
  printf((char const   * __restrict  )"Create second level with length %d\n", 3);
  lvl = create_lvl(3);
  logBlockEntry("mbg-skip-with-dll-children.c", 93);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 93, & lvl, "struct skip_node *",
                    "lvl", lvl, "struct skip_node", "create_lvl", 0);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 94);
  printf((char const   * __restrict  )"Connect level one and two\n");
  conn_two_lvls(sk_ep, lvl, conn_lvl1_to_lvl2, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 96);
  printf((char const   * __restrict  )"Create third level with length %d\n", 4);
  lvl = create_lvl(4);
  logBlockEntry("mbg-skip-with-dll-children.c", 97);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 97, & lvl, "struct skip_node *",
                    "lvl", lvl, "struct skip_node", "create_lvl", 0);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 98);
  printf((char const   * __restrict  )"Connect level two and three\n");
  conn_two_lvls(sk_ep->down, lvl, conn_lvl2_to_lvl3, 3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 101);
  printf((char const   * __restrict  )"Create first payload\n");
  logBlockEntry("mbg-skip-with-dll-children.c", 102);
  tmp = lvl;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 102, & tmp, "struct skip_node *",
                    "tmp", tmp, "struct skip_node", "lvl", 0);
  tmp___0 = malloc(sizeof(*(tmp->payload)));
  logAssignNoOffset("mbg-skip-with-dll-children.c", 103, & tmp___0, "void *", "tmp___0",
                    tmp___0, "void", "malloc", 1);
  logMallocInfo("sizeof(*(tmp->payload))", sizeof(*(tmp->payload)));
  tmp->payload = (struct dll_node *)tmp___0;
  logAssignOffset("mbg-skip-with-dll-children.c", 103, tmp, "struct skip_node", "*tmp",
                  & tmp->payload, "struct dll_node *", "tmp->payload", tmp->payload,
                  "struct dll_node", "(struct dll_node *)tmp___0", 0);
  logBlockExit("mbg-skip-with-dll-children.c", 104);
  create_dll(tmp->payload, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 106);
  printf((char const   * __restrict  )"Create second payload\n");
  logBlockEntry("mbg-skip-with-dll-children.c", 108);
  tmp = tmp->next;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 108, & tmp, "struct skip_node *",
                    "tmp", tmp, "struct skip_node", "tmp->next", 0);
  tmp___1 = malloc(sizeof(*(tmp->payload)));
  logAssignNoOffset("mbg-skip-with-dll-children.c", 109, & tmp___1, "void *", "tmp___1",
                    tmp___1, "void", "malloc", 1);
  logMallocInfo("sizeof(*(tmp->payload))", sizeof(*(tmp->payload)));
  tmp->payload = (struct dll_node *)tmp___1;
  logAssignOffset("mbg-skip-with-dll-children.c", 109, tmp, "struct skip_node", "*tmp",
                  & tmp->payload, "struct dll_node *", "tmp->payload", tmp->payload,
                  "struct dll_node", "(struct dll_node *)tmp___1", 0);
  logBlockExit("mbg-skip-with-dll-children.c", 110);
  create_dll(tmp->payload, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("mbg-skip-with-dll-children.c", 112);
  printf((char const   * __restrict  )"Create third payload\n");
  logBlockEntry("mbg-skip-with-dll-children.c", 114);
  tmp = tmp->next;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 114, & tmp, "struct skip_node *",
                    "tmp", tmp, "struct skip_node", "tmp->next", 0);
  tmp = tmp->next;
  logAssignNoOffset("mbg-skip-with-dll-children.c", 115, & tmp, "struct skip_node *",
                    "tmp", tmp, "struct skip_node", "tmp->next", 0);
  tmp___2 = malloc(sizeof(*(tmp->payload)));
  logAssignNoOffset("mbg-skip-with-dll-children.c", 116, & tmp___2, "void *", "tmp___2",
                    tmp___2, "void", "malloc", 1);
  logMallocInfo("sizeof(*(tmp->payload))", sizeof(*(tmp->payload)));
  tmp->payload = (struct dll_node *)tmp___2;
  logAssignOffset("mbg-skip-with-dll-children.c", 116, tmp, "struct skip_node", "*tmp",
                  & tmp->payload, "struct dll_node *", "tmp->payload", tmp->payload,
                  "struct dll_node", "(struct dll_node *)tmp___2", 0);
  logBlockExit("mbg-skip-with-dll-children.c", 117);
  create_dll(tmp->payload, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  lvl = (struct skip_node *)((void *)0);
  logAssignNoOffset("mbg-skip-with-dll-children.c", 119, & lvl, "struct skip_node *",
                    "lvl", lvl, "struct skip_node", "(struct skip_node *)((void *)0)",
                    0);
  logBlockExit("mbg-skip-with-dll-children.c", 119);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("sk_ep", & sk_ep);
  logVarOutOfScope("lvl", & lvl);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("tmp___2", & tmp___2);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
