/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int item ;
   struct node *next ;
   struct node *prev ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
void insertHead(struct node **head , struct node **tail , int item ) ;
void insertHead(struct node **head , struct node **tail , int item ) 
{ 
  struct node *node ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "head", "struct node **", & head);
  logVarInScope("formal", "tail", "struct node **", & tail);
  logVarInScope("local", "node", "struct node *", & node);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_5.c", 15);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("dll_5.c", 15, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  node = (struct node *)tmp;
  logAssignNoOffset("dll_5.c", 15, & node, "struct node *", "node", node, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("dll_5.c", 15);
  if ((unsigned long )node == (unsigned long )((void *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_5.c", 17);
  node->item = item;
  node->prev = (struct node *)((void *)0);
  logAssignOffset("dll_5.c", 18, node, "struct node", "*node", & node->prev, "struct node *",
                  "node->prev", node->prev, "struct node", "(struct node *)((void *)0)",
                  0);
  logBlockExit("dll_5.c", 18);
  if ((unsigned long )*head == (unsigned long )((void *)0)) {
    if ((unsigned long )*tail == (unsigned long )((void *)0)) {
      logBlockEntry("dll_5.c", 20);
      node->next = (struct node *)((void *)0);
      logAssignOffset("dll_5.c", 20, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "(struct node *)((void *)0)",
                      0);
      *head = node;
      logAssignNoOffset("dll_5.c", 21, & *head, "struct node *", "*head", *head, "struct node",
                        "node", 0);
      *tail = node;
      logAssignNoOffset("dll_5.c", 22, & *tail, "struct node *", "*tail", *tail, "struct node",
                        "node", 0);
      logBlockExit("dll_5.c", 22);
    } else {
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
  if ((unsigned long )*head != (unsigned long )((void *)0)) {
    if ((unsigned long )*tail != (unsigned long )((void *)0)) {
      logBlockEntry("dll_5.c", 24);
      node->next = *head;
      logAssignOffset("dll_5.c", 24, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "*head", 0);
      (*head)->prev = node;
      logAssignOffset("dll_5.c", 25, *head, "struct node", "*(*head)", & (*head)->prev,
                      "struct node *", "(*head)->prev", (*head)->prev, "struct node",
                      "node", 0);
      *head = node;
      logAssignNoOffset("dll_5.c", 26, & *head, "struct node *", "*head", *head, "struct node",
                        "node", 0);
      logBlockExit("dll_5.c", 26);
    } else {
      abort();
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    }
  } else {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("head", & head);
  logVarOutOfScope("tail", & tail);
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(void) 
{ 
  struct node *head ;
  struct node *tail ;

  {
  logComment("Function Entered");
  logVarInScope("local", "head", "struct node *", & head);
  logVarInScope("local", "tail", "struct node *", & tail);
  logBlockEntry("dll_5.c", 36);
  head = (struct node *)((void *)0);
  logAssignNoOffset("dll_5.c", 36, & head, "struct node *", "head", head, "struct node",
                    "(struct node *)((void *)0)", 0);
  tail = (struct node *)((void *)0);
  logAssignNoOffset("dll_5.c", 37, & tail, "struct node *", "tail", tail, "struct node",
                    "(struct node *)((void *)0)", 0);
  logBlockExit("dll_5.c", 39);
  insertHead(& head, & tail, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_5.c", 40);
  insertHead(& head, & tail, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_5.c", 41);
  insertHead(& head, & tail, 3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_5.c", 42);
  insertHead(& head, & tail, 4);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_5.c", 43);
  insertHead(& head, & tail, 5);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("head", & head);
  logVarOutOfScope("tail", & tail);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
