/* Generated by CIL v. 1.7.2 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int payload ;
   struct node *next ;
   struct node *link ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
struct node *head  =    (struct node *)((void *)0);
void insert(struct node *cur_elem ) 
{ 
  void *tmp ;
  void *tmp___0 ;

  {
  logComment("Function Entered");
  if ((unsigned long )cur_elem != (unsigned long )((void *)0)) {
    logBlockEntry("leak-3-free.c", 24);
    tmp = malloc(sizeof(struct node ));
    logAssignNoOffset("leak-3-free.c", 24, & tmp, "void *", "tmp", tmp, "void", "malloc",
                      1);
    logMallocInfo("sizeof(struct node )", sizeof(struct node ));
    cur_elem->next = (struct node *)tmp;
    logAssignOffset("leak-3-free.c", 24, cur_elem, "struct node", "*cur_elem", & cur_elem->next,
                    "struct node *", "cur_elem->next", cur_elem->next, "struct node",
                    "(struct node *)tmp", 0);
    logBlockExit("leak-3-free.c", 24);
    if ((unsigned long )cur_elem->next == (unsigned long )((void *)0)) {
      printf((char const   * __restrict  )"Error: No space left. Exiting.");
      exit(1);
    }
    logBlockEntry("leak-3-free.c", 29);
    (cur_elem->next)->next = (struct node *)((void *)0);
    logAssignOffset("leak-3-free.c", 29, cur_elem->next, "struct node", "*(cur_elem->next)",
                    & (cur_elem->next)->next, "struct node *", "(cur_elem->next)->next",
                    (cur_elem->next)->next, "struct node", "(struct node *)((void *)0)",
                    0);
    logBlockExit("leak-3-free.c", 29);
  } else {
    logBlockEntry("leak-3-free.c", 32);
    tmp___0 = malloc(sizeof(struct node ));
    logAssignNoOffset("leak-3-free.c", 32, & tmp___0, "void *", "tmp___0", tmp___0,
                      "void", "malloc", 1);
    logMallocInfo("sizeof(struct node )", sizeof(struct node ));
    head = (struct node *)tmp___0;
    logAssignNoOffset("leak-3-free.c", 32, & head, "struct node *", "head", head,
                      "struct node", "(struct node *)tmp___0", 0);
    logBlockExit("leak-3-free.c", 32);
    if ((unsigned long )head == (unsigned long )((void *)0)) {
      printf((char const   * __restrict  )"Error: No space left. Exiting.");
      exit(1);
    }
    logBlockEntry("leak-3-free.c", 37);
    head->next = (struct node *)((void *)0);
    logAssignOffset("leak-3-free.c", 37, head, "struct node", "*head", & head->next,
                    "struct node *", "head->next", head->next, "struct node", "(struct node *)((void *)0)",
                    0);
    logBlockExit("leak-3-free.c", 37);
  }
  {
  logVarOutOfScope("cur_elem", & cur_elem);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(int argc , char **argv ) 
{ 
  struct node *iter ;
  int i ;
  void *tmp ;

  {
  logComment("Function Entered");
  logBlockEntry("leak-3-free.c", 45);
  i = 0;
  logBlockExit("leak-3-free.c", 48);
  insert((struct node *)((void *)0));
  logBlockEntry("leak-3-free.c", 50);
  iter = head;
  logAssignNoOffset("leak-3-free.c", 50, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  iter->payload = i;
  logBlockExit("leak-3-free.c", 51);
  while (i < 5) {
    logComment("Loop-iteration-start_leak-3-free.c_52");
    {
    printf((char const   * __restrict  )"Inserting element(%d)\n", i);
    insert(iter);
    logBlockEntry("leak-3-free.c", 55);
    iter->payload = i;
    iter = iter->next;
    logAssignNoOffset("leak-3-free.c", 56, & iter, "struct node *", "iter", iter,
                      "struct node", "iter->next", 0);
    i ++;
    logBlockExit("leak-3-free.c", 52);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("leak-3-free.c", 60);
  i = 0;
  iter = head;
  logAssignNoOffset("leak-3-free.c", 61, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  logBlockExit("leak-3-free.c", 61);
  while (i < 3) {
    logComment("Loop-iteration-start_leak-3-free.c_62");
    {
    printf((char const   * __restrict  )"Forwarding element(%d)\n", i);
    logBlockEntry("leak-3-free.c", 64);
    iter = iter->next;
    logAssignNoOffset("leak-3-free.c", 64, & iter, "struct node *", "iter", iter,
                      "struct node", "iter->next", 0);
    i ++;
    logBlockExit("leak-3-free.c", 62);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("leak-3-free.c", 68);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("leak-3-free.c", 68, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  (iter->next)->link = (struct node *)tmp;
  logAssignOffset("leak-3-free.c", 68, iter->next, "struct node", "*(iter->next)",
                  & (iter->next)->link, "struct node *", "(iter->next)->link", (iter->next)->link,
                  "struct node", "(struct node *)tmp", 0);
  logBlockExit("leak-3-free.c", 68);
  if ((unsigned long )(iter->next)->link == (unsigned long )((void *)0)) {
    printf((char const   * __restrict  )"Error: No space left. Exiting.");
    exit(1);
  }
  insert((iter->next)->link);
  insert(((iter->next)->link)->next);
  logBlockEntry("leak-3-free.c", 76);
  (((iter->next)->link)->next)->next = iter;
  logAssignOffset("leak-3-free.c", 76, ((iter->next)->link)->next, "struct node",
                  "*(((iter->next)->link)->next)", & (((iter->next)->link)->next)->next,
                  "struct node *", "(((iter->next)->link)->next)->next", (((iter->next)->link)->next)->next,
                  "struct node", "iter", 0);
  logFree("leak-3-free.c", 79, "(void *)iter->next", (void *)iter->next);
  free((void *)iter->next);
  iter = head;
  logAssignNoOffset("leak-3-free.c", 83, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  logBlockExit("leak-3-free.c", 83);
  while ((unsigned long )iter != (unsigned long )((void *)0)) {
    logComment("Loop-iteration-start_leak-3-free.c_84");
    {
    printf((char const   * __restrict  )"Freeing element\n");
    logBlockEntry("leak-3-free.c", 86);
    head = iter->next;
    logAssignNoOffset("leak-3-free.c", 86, & head, "struct node *", "head", head,
                      "struct node", "iter->next", 0);
    logFree("leak-3-free.c", 87, "(void *)iter", (void *)iter);
    free((void *)iter);
    iter = head;
    logAssignNoOffset("leak-3-free.c", 88, & iter, "struct node *", "iter", iter,
                      "struct node", "head", 0);
    logBlockExit("leak-3-free.c", 88);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("iter", & iter);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
