/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int item ;
   struct node *next ;
   struct node *prev ;
};
struct dll {
   struct node *head ;
   struct node *tail ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
void insertHead(struct dll **dll , int item ) ;
void insertHead(struct dll **dll , int item ) 
{ 
  struct node *node ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "dll", "struct dll **", & dll);
  logVarInScope("local", "node", "struct node *", & node);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_4.c", 20);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("dll_4.c", 20, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  node = (struct node *)tmp;
  logAssignNoOffset("dll_4.c", 20, & node, "struct node *", "node", node, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("dll_4.c", 20);
  if ((unsigned long )node == (unsigned long )((void *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_4.c", 22);
  node->item = item;
  node->prev = (struct node *)((void *)0);
  logAssignOffset("dll_4.c", 23, node, "struct node", "*node", & node->prev, "struct node *",
                  "node->prev", node->prev, "struct node", "(struct node *)((void *)0)",
                  0);
  logBlockExit("dll_4.c", 23);
  if ((unsigned long )(*dll)->head == (unsigned long )((void *)0)) {
    if ((unsigned long )(*dll)->tail == (unsigned long )((void *)0)) {
      logBlockEntry("dll_4.c", 25);
      node->next = (struct node *)((void *)0);
      logAssignOffset("dll_4.c", 25, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "(struct node *)((void *)0)",
                      0);
      (*dll)->head = node;
      logAssignOffset("dll_4.c", 26, *dll, "struct dll", "*(*dll)", & (*dll)->head,
                      "struct node *", "(*dll)->head", (*dll)->head, "struct node",
                      "node", 0);
      (*dll)->tail = node;
      logAssignOffset("dll_4.c", 27, *dll, "struct dll", "*(*dll)", & (*dll)->tail,
                      "struct node *", "(*dll)->tail", (*dll)->tail, "struct node",
                      "node", 0);
      logBlockExit("dll_4.c", 27);
    } else {
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
  if ((unsigned long )(*dll)->head != (unsigned long )((void *)0)) {
    if ((unsigned long )(*dll)->tail != (unsigned long )((void *)0)) {
      logBlockEntry("dll_4.c", 29);
      node->next = (*dll)->head;
      logAssignOffset("dll_4.c", 29, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "(*dll)->head", 0);
      ((*dll)->head)->prev = node;
      logAssignOffset("dll_4.c", 30, (*dll)->head, "struct node", "*((*dll)->head)",
                      & ((*dll)->head)->prev, "struct node *", "((*dll)->head)->prev",
                      ((*dll)->head)->prev, "struct node", "node", 0);
      (*dll)->head = node;
      logAssignOffset("dll_4.c", 31, *dll, "struct dll", "*(*dll)", & (*dll)->head,
                      "struct node *", "(*dll)->head", (*dll)->head, "struct node",
                      "node", 0);
      logBlockExit("dll_4.c", 31);
    } else {
      abort();
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    }
  } else {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(void) 
{ 
  struct dll *dllPointer ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "dllPointer", "struct dll *", & dllPointer);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_4.c", 41);
  tmp = malloc(sizeof(struct dll ));
  logAssignNoOffset("dll_4.c", 41, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct dll )", sizeof(struct dll ));
  dllPointer = (struct dll *)tmp;
  logAssignNoOffset("dll_4.c", 41, & dllPointer, "struct dll *", "dllPointer", dllPointer,
                    "struct dll", "(struct dll *)tmp", 0);
  logBlockExit("dll_4.c", 41);
  if ((unsigned long )dllPointer == (unsigned long )((void *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_4.c", 43);
  dllPointer->head = (struct node *)((void *)0);
  logAssignOffset("dll_4.c", 43, dllPointer, "struct dll", "*dllPointer", & dllPointer->head,
                  "struct node *", "dllPointer->head", dllPointer->head, "struct node",
                  "(struct node *)((void *)0)", 0);
  dllPointer->tail = (struct node *)((void *)0);
  logAssignOffset("dll_4.c", 44, dllPointer, "struct dll", "*dllPointer", & dllPointer->tail,
                  "struct node *", "dllPointer->tail", dllPointer->tail, "struct node",
                  "(struct node *)((void *)0)", 0);
  logBlockExit("dll_4.c", 46);
  insertHead(& dllPointer, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_4.c", 47);
  insertHead(& dllPointer, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_4.c", 48);
  insertHead(& dllPointer, 3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_4.c", 49);
  insertHead(& dllPointer, 4);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_4.c", 50);
  insertHead(& dllPointer, 5);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("dllPointer", & dllPointer);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
