/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   struct node *next ;
   int value ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
struct node *node_malloc(int item ) ;
void list_add(struct node **l , struct node *new ) ;
void list_dispose(struct node *current ) ;
void list_add(struct node **l , struct node *new ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct node **", & l);
  logVarInScope("formal", "new", "struct node *", & new);
  logBlockEntry("sll_9.c", 17);
  new->next = *l;
  logAssignOffset("sll_9.c", 17, new, "struct node", "*new", & new->next, "struct node *",
                  "new->next", new->next, "struct node", "*l", 0);
  *l = new;
  logAssignNoOffset("sll_9.c", 18, & *l, "struct node *", "*l", *l, "struct node",
                    "new", 0);
  logBlockExit("sll_9.c", 18);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("new", & new);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void list_dispose(struct node *current ) 
{ 
  struct node *oldcurrent ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "current", "struct node *", & current);
  logVarInScope("local", "oldcurrent", "struct node *", & oldcurrent);
  while ((unsigned long )current != (unsigned long )((struct node *)0)) {
    logComment("Loop-iteration-start_sll_9.c_23");
    {
    logBlockEntry("sll_9.c", 25);
    oldcurrent = current;
    logAssignNoOffset("sll_9.c", 25, & oldcurrent, "struct node *", "oldcurrent",
                      oldcurrent, "struct node", "current", 0);
    current = current->next;
    logAssignNoOffset("sll_9.c", 26, & current, "struct node *", "current", current,
                      "struct node", "current->next", 0);
    logFree("sll_9.c", 27, "(void *)oldcurrent", (void *)oldcurrent);
    free((void *)oldcurrent);
    logBlockExit("sll_9.c", 27);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("current", & current);
  logVarOutOfScope("oldcurrent", & oldcurrent);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
struct node *node_malloc(int item ) 
{ 
  struct node *new ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "new", "struct node *", & new);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("sll_9.c", 35);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("sll_9.c", 35, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  new = (struct node *)tmp;
  logAssignNoOffset("sll_9.c", 35, & new, "struct node *", "new", new, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("sll_9.c", 35);
  if ((unsigned long )new == (unsigned long )((struct node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_9.c", 37);
  new->next = (struct node *)0;
  logAssignOffset("sll_9.c", 37, new, "struct node", "*new", & new->next, "struct node *",
                  "new->next", new->next, "struct node", "(struct node *)0", 0);
  new->value = item;
  logBlockExit("sll_9.c", 38);
  {
  logVarOutOfScope("new", & new);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (new);
  }
  }
}
}
int main(void) 
{ 
  struct node *l ;
  struct node *n1 ;
  struct node *tmp ;
  struct node *n2 ;
  struct node *tmp___0 ;
  struct node *n3 ;
  struct node *tmp___1 ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "struct node *", & l);
  logVarInScope("local", "n1", "struct node *", & n1);
  logVarInScope("local", "tmp", "struct node *", & tmp);
  logVarInScope("local", "n2", "struct node *", & n2);
  logVarInScope("local", "tmp___0", "struct node *", & tmp___0);
  logVarInScope("local", "n3", "struct node *", & n3);
  logVarInScope("local", "tmp___1", "struct node *", & tmp___1);
  logBlockEntry("sll_9.c", 46);
  l = (struct node *)((void *)0);
  logAssignNoOffset("sll_9.c", 46, & l, "struct node *", "l", l, "struct node", "(struct node *)((void *)0)",
                    0);
  logBlockExit("sll_9.c", 47);
  tmp = node_malloc(1);
  logBlockEntry("sll_9.c", 47);
  logAssignNoOffset("sll_9.c", 47, & tmp, "struct node *", "tmp", tmp, "struct node",
                    "node_malloc", 0);
  dumpVarsOutOfScope();
  n1 = tmp;
  logAssignNoOffset("sll_9.c", 47, & n1, "struct node *", "n1", n1, "struct node",
                    "tmp", 0);
  logBlockExit("sll_9.c", 48);
  tmp___0 = node_malloc(2);
  logBlockEntry("sll_9.c", 48);
  logAssignNoOffset("sll_9.c", 48, & tmp___0, "struct node *", "tmp___0", tmp___0,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n2 = tmp___0;
  logAssignNoOffset("sll_9.c", 48, & n2, "struct node *", "n2", n2, "struct node",
                    "tmp___0", 0);
  logBlockExit("sll_9.c", 49);
  tmp___1 = node_malloc(3);
  logBlockEntry("sll_9.c", 49);
  logAssignNoOffset("sll_9.c", 49, & tmp___1, "struct node *", "tmp___1", tmp___1,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n3 = tmp___1;
  logAssignNoOffset("sll_9.c", 49, & n3, "struct node *", "n3", n3, "struct node",
                    "tmp___1", 0);
  logBlockExit("sll_9.c", 50);
  list_add(& l, n1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_9.c", 51);
  list_add(& l, n2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_9.c", 52);
  list_add(& l, n3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_9.c", 53);
  list_dispose(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("n1", & n1);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("n2", & n2);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("n3", & n3);
  logVarOutOfScope("tmp___1", & tmp___1);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
