/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct _dll {
   int payload ;
   struct _dll *next ;
   struct _dll *prev ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
int main(int argc , char **argv ) 
{ 
  struct _dll *sim_stack ;
  void *tmp ;
  struct _dll *head ;
  void *tmp___0 ;
  struct _dll *node ;
  void *tmp___1 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "sim_stack", "struct _dll *", & sim_stack);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "head", "struct _dll *", & head);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logVarInScope("local", "node", "struct _dll *", & node);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logBlockEntry("cdll-corner-case.c", 15);
  tmp = malloc(sizeof(struct _dll ));
  logAssignNoOffset("cdll-corner-case.c", 15, & tmp, "void *", "tmp", tmp, "void",
                    "malloc", 1);
  logMallocInfo("sizeof(struct _dll )", sizeof(struct _dll ));
  sim_stack = (struct _dll *)tmp;
  logAssignNoOffset("cdll-corner-case.c", 15, & sim_stack, "struct _dll *", "sim_stack",
                    sim_stack, "struct _dll", "(struct _dll *)tmp", 0);
  tmp___0 = malloc(sizeof(struct _dll ));
  logAssignNoOffset("cdll-corner-case.c", 16, & tmp___0, "void *", "tmp___0", tmp___0,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct _dll )", sizeof(struct _dll ));
  head = (struct _dll *)tmp___0;
  logAssignNoOffset("cdll-corner-case.c", 16, & head, "struct _dll *", "head", head,
                    "struct _dll", "(struct _dll *)tmp___0", 0);
  tmp___1 = malloc(sizeof(struct _dll ));
  logAssignNoOffset("cdll-corner-case.c", 17, & tmp___1, "void *", "tmp___1", tmp___1,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct _dll )", sizeof(struct _dll ));
  node = (struct _dll *)tmp___1;
  logAssignNoOffset("cdll-corner-case.c", 17, & node, "struct _dll *", "node", node,
                    "struct _dll", "(struct _dll *)tmp___1", 0);
  sim_stack->next = head;
  logAssignOffset("cdll-corner-case.c", 18, sim_stack, "struct _dll", "*sim_stack",
                  & sim_stack->next, "struct _dll *", "sim_stack->next", sim_stack->next,
                  "struct _dll", "head", 0);
  node->next = head;
  logAssignOffset("cdll-corner-case.c", 19, node, "struct _dll", "*node", & node->next,
                  "struct _dll *", "node->next", node->next, "struct _dll", "head",
                  0);
  node->prev = head;
  logAssignOffset("cdll-corner-case.c", 20, node, "struct _dll", "*node", & node->prev,
                  "struct _dll *", "node->prev", node->prev, "struct _dll", "head",
                  0);
  head->next = node;
  logAssignOffset("cdll-corner-case.c", 21, head, "struct _dll", "*head", & head->next,
                  "struct _dll *", "head->next", head->next, "struct _dll", "node",
                  0);
  logBlockExit("cdll-corner-case.c", 21);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("sim_stack", & sim_stack);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("head", & head);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp___1", & tmp___1);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
