/* Generated by CIL v. 1.7.2 */
/* print_CIL_Input is true */

typedef int ElementType;
struct Linkage_Struct;
typedef struct Linkage_Struct *LinkPtr;
struct Linkage_Struct {
   LinkPtr Next ;
   ElementType Load ;
};
typedef struct Linkage_Struct Link;
struct Weiss_SLL_Node {
   ElementType Load01 ;
   Link Link01 ;
   ElementType Load02 ;
   Link Link02 ;
};
typedef struct Weiss_SLL_Node Node;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
int main(int argc , char **argv ) 
{ 
  Node node01 ;
  Node node02 ;
  Node node03 ;
  Node node04 ;
  LinkPtr head ;
  LinkPtr iter ;

  {
  logComment("Function Entered");
  logBlockEntry("ept-test.c", 37);
  head = & node01.Link01;
  logAssignNoOffset("ept-test.c", 37, & head, "struct Linkage_Struct *", "head", head,
                    "struct Linkage_Struct", "& node01.Link01", 0);
  node01.Link01.Next = & node02.Link01;
  logAssignOffset("ept-test.c", 39, & node01, "struct Weiss_SLL_Node", "node01", & node01.Link01.Next,
                  "struct Linkage_Struct *", "node01.Link01.Next", node01.Link01.Next,
                  "struct Linkage_Struct", "& node02.Link01", 0);
  node02.Link01.Next = & node03.Link01;
  logAssignOffset("ept-test.c", 40, & node02, "struct Weiss_SLL_Node", "node02", & node02.Link01.Next,
                  "struct Linkage_Struct *", "node02.Link01.Next", node02.Link01.Next,
                  "struct Linkage_Struct", "& node03.Link01", 0);
  node03.Link01.Next = (LinkPtr )((void *)0);
  logAssignOffset("ept-test.c", 41, & node03, "struct Weiss_SLL_Node", "node03", & node03.Link01.Next,
                  "struct Linkage_Struct *", "node03.Link01.Next", node03.Link01.Next,
                  "struct Linkage_Struct", "(LinkPtr )((void *)0)", 0);
  iter = & node01.Link01;
  logAssignNoOffset("ept-test.c", 43, & iter, "struct Linkage_Struct *", "iter", iter,
                    "struct Linkage_Struct", "& node01.Link01", 0);
  logBlockExit("ept-test.c", 43);
  while ((unsigned long )iter->Next != (unsigned long )((void *)0)) {
    logComment("Loop-iteration-start_ept-test.c_44");
    {
    logBlockEntry("ept-test.c", 45);
    iter = iter->Next;
    logAssignNoOffset("ept-test.c", 45, & iter, "struct Linkage_Struct *", "iter",
                      iter, "struct Linkage_Struct", "iter->Next", 0);
    logBlockExit("ept-test.c", 46);
    printf((char const   * __restrict  )"Iterating...\n");
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("ept-test.c", 49);
  node03.Link01.Next = & node04.Link01;
  logAssignOffset("ept-test.c", 49, & node03, "struct Weiss_SLL_Node", "node03", & node03.Link01.Next,
                  "struct Linkage_Struct *", "node03.Link01.Next", node03.Link01.Next,
                  "struct Linkage_Struct", "& node04.Link01", 0);
  logBlockExit("ept-test.c", 49);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("node01", & node01);
  logVarOutOfScope("node02", & node02);
  logVarOutOfScope("node03", & node03);
  logVarOutOfScope("node04", & node04);
  logVarOutOfScope("head", & head);
  logVarOutOfScope("iter", & iter);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
