/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct binary_tree {
   int payload ;
   struct binary_tree *left ;
   struct binary_tree *right ;
   struct binary_tree *sll ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
void insert(struct binary_tree *root , struct binary_tree *element ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "root", "struct binary_tree *", & root);
  logVarInScope("formal", "element", "struct binary_tree *", & element);
  if (element->payload < root->payload) {
    if ((unsigned long )root->left != (unsigned long )((void *)0)) {
      insert(root->left, element);
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    } else {
      logBlockEntry("binary-tree-linked-leaves.c", 18);
      root->left = element;
      logAssignOffset("binary-tree-linked-leaves.c", 18, root, "struct binary_tree",
                      "*root", & root->left, "struct binary_tree *", "root->left",
                      root->left, "struct binary_tree", "element", 0);
      logBlockExit("binary-tree-linked-leaves.c", 18);
    }
  } else
  if (element->payload > root->payload) {
    if ((unsigned long )root->right != (unsigned long )((void *)0)) {
      insert(root->right, element);
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    } else {
      logBlockEntry("binary-tree-linked-leaves.c", 24);
      root->right = element;
      logAssignOffset("binary-tree-linked-leaves.c", 24, root, "struct binary_tree",
                      "*root", & root->right, "struct binary_tree *", "root->right",
                      root->right, "struct binary_tree", "element", 0);
      logBlockExit("binary-tree-linked-leaves.c", 24);
    }
  }
  {
  logVarOutOfScope("root", & root);
  logVarOutOfScope("element", & element);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
void print_tree(struct binary_tree *root , struct binary_tree **leaf_sll , struct binary_tree **last_leaf ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "root", "struct binary_tree *", & root);
  logVarInScope("formal", "leaf_sll", "struct binary_tree **", & leaf_sll);
  logVarInScope("formal", "last_leaf", "struct binary_tree **", & last_leaf);
  if ((unsigned long )root->left == (unsigned long )((void *)0)) {
    if ((unsigned long )root->right == (unsigned long )((void *)0)) {
      printf((char const   * __restrict  )"[connecting leafs: ");
      if ((unsigned long )*last_leaf == (unsigned long )((void *)0)) {
        printf((char const   * __restrict  )"init]");
        logBlockEntry("binary-tree-linked-leaves.c", 35);
        *last_leaf = root;
        logAssignNoOffset("binary-tree-linked-leaves.c", 35, & *last_leaf, "struct binary_tree *",
                          "*last_leaf", *last_leaf, "struct binary_tree", "root",
                          0);
        *leaf_sll = root;
        logAssignNoOffset("binary-tree-linked-leaves.c", 36, & *leaf_sll, "struct binary_tree *",
                          "*leaf_sll", *leaf_sll, "struct binary_tree", "root", 0);
        logBlockExit("binary-tree-linked-leaves.c", 36);
      } else {
        printf((char const   * __restrict  )" sll]");
        logBlockEntry("binary-tree-linked-leaves.c", 39);
        (*last_leaf)->sll = root;
        logAssignOffset("binary-tree-linked-leaves.c", 39, *last_leaf, "struct binary_tree",
                        "*(*last_leaf)", & (*last_leaf)->sll, "struct binary_tree *",
                        "(*last_leaf)->sll", (*last_leaf)->sll, "struct binary_tree",
                        "root", 0);
        *last_leaf = root;
        logAssignNoOffset("binary-tree-linked-leaves.c", 40, & *last_leaf, "struct binary_tree *",
                          "*last_leaf", *last_leaf, "struct binary_tree", "root",
                          0);
        logBlockExit("binary-tree-linked-leaves.c", 40);
      }
    }
  }
  if ((unsigned long )root->left != (unsigned long )((void *)0)) {
    printf((char const   * __restrict  )"[l]");
    print_tree(root->left, leaf_sll, last_leaf);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  printf((char const   * __restrict  )"%d\n", root->payload);
  if ((unsigned long )root->right != (unsigned long )((void *)0)) {
    printf((char const   * __restrict  )"[r]");
    print_tree(root->right, leaf_sll, last_leaf);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("root", & root);
  logVarOutOfScope("leaf_sll", & leaf_sll);
  logVarOutOfScope("last_leaf", & last_leaf);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int main(int argc , char **argv ) 
{ 
  int payload[14] ;
  int root_payload ;
  int payload_len ;
  struct binary_tree *root ;
  struct binary_tree *elem_tmp ;
  void *tmp ;
  struct binary_tree *tmp___0 ;
  int i ;
  void *tmp___1 ;
  struct binary_tree *leaf_sll ;
  struct binary_tree *last_leaf ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "root", "struct binary_tree *", & root);
  logVarInScope("local", "elem_tmp", "struct binary_tree *", & elem_tmp);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "tmp___0", "struct binary_tree *", & tmp___0);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logVarInScope("local", "leaf_sll", "struct binary_tree *", & leaf_sll);
  logVarInScope("local", "last_leaf", "struct binary_tree *", & last_leaf);
  logBlockEntry("binary-tree-linked-leaves.c", 58);
  payload[0] = 20;
  payload[1] = 10;
  payload[2] = 5;
  payload[3] = 15;
  payload[4] = 30;
  payload[5] = 25;
  payload[6] = 35;
  payload[7] = 60;
  payload[8] = 50;
  payload[9] = 45;
  payload[10] = 55;
  payload[11] = 70;
  payload[12] = 65;
  payload[13] = 75;
  root_payload = 40;
  payload_len = 14;
  tmp = malloc(sizeof(*root));
  logAssignNoOffset("binary-tree-linked-leaves.c", 64, & tmp, "void *", "tmp", tmp,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(*root)", sizeof(*root));
  root = (struct binary_tree *)tmp;
  logAssignNoOffset("binary-tree-linked-leaves.c", 64, & root, "struct binary_tree *",
                    "root", root, "struct binary_tree", "(struct binary_tree *)tmp",
                    0);
  tmp___0 = (struct binary_tree *)((void *)0);
  logAssignNoOffset("binary-tree-linked-leaves.c", 65, & tmp___0, "struct binary_tree *",
                    "tmp___0", tmp___0, "struct binary_tree", "(struct binary_tree *)((void *)0)",
                    0);
  root->right = tmp___0;
  logAssignOffset("binary-tree-linked-leaves.c", 65, root, "struct binary_tree", "*root",
                  & root->right, "struct binary_tree *", "root->right", root->right,
                  "struct binary_tree", "tmp___0", 0);
  root->left = tmp___0;
  logAssignOffset("binary-tree-linked-leaves.c", 65, root, "struct binary_tree", "*root",
                  & root->left, "struct binary_tree *", "root->left", root->left,
                  "struct binary_tree", "tmp___0", 0);
  root->payload = root_payload;
  i = 0;
  logBlockExit("binary-tree-linked-leaves.c", 68);
  while (i < payload_len) {
    logComment("Loop-iteration-start_binary-tree-linked-leaves.c_68");
    {
    logBlockEntry("binary-tree-linked-leaves.c", 69);
    tmp___1 = malloc(sizeof(*elem_tmp));
    logAssignNoOffset("binary-tree-linked-leaves.c", 69, & tmp___1, "void *", "tmp___1",
                      tmp___1, "void", "malloc", 1);
    logMallocInfo("sizeof(*elem_tmp)", sizeof(*elem_tmp));
    elem_tmp = (struct binary_tree *)tmp___1;
    logAssignNoOffset("binary-tree-linked-leaves.c", 69, & elem_tmp, "struct binary_tree *",
                      "elem_tmp", elem_tmp, "struct binary_tree", "(struct binary_tree *)tmp___1",
                      0);
    elem_tmp->payload = payload[i];
    logBlockExit("binary-tree-linked-leaves.c", 71);
    insert(root, elem_tmp);
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    i ++;
    logBlockExit("binary-tree-linked-leaves.c", 68);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("binary-tree-linked-leaves.c", 75);
  last_leaf = (struct binary_tree *)((void *)0);
  logAssignNoOffset("binary-tree-linked-leaves.c", 75, & last_leaf, "struct binary_tree *",
                    "last_leaf", last_leaf, "struct binary_tree", "(struct binary_tree *)((void *)0)",
                    0);
  logBlockExit("binary-tree-linked-leaves.c", 76);
  print_tree(root, & leaf_sll, & last_leaf);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("binary-tree-linked-leaves.c", 78);
  printf((char const   * __restrict  )"print leaf sll: \n");
  while (leaf_sll) {
    logComment("Loop-iteration-start_binary-tree-linked-leaves.c_79");
    {
    printf((char const   * __restrict  )"%d,", leaf_sll->payload);
    logBlockEntry("binary-tree-linked-leaves.c", 81);
    leaf_sll = leaf_sll->sll;
    logAssignNoOffset("binary-tree-linked-leaves.c", 81, & leaf_sll, "struct binary_tree *",
                      "leaf_sll", leaf_sll, "struct binary_tree", "leaf_sll->sll",
                      0);
    logBlockExit("binary-tree-linked-leaves.c", 81);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("root", & root);
  logVarOutOfScope("elem_tmp", & elem_tmp);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("leaf_sll", & leaf_sll);
  logVarOutOfScope("last_leaf", & last_leaf);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
