/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
int main(int argc , char **argv ) 
{ 
  int count ;
  char *pointer ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "pointer", "char *", & pointer);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("leak-7-ptr-no-ds.c", 11);
  count = 0;
  pointer = (char *)((void *)0);
  logAssignNoOffset("leak-7-ptr-no-ds.c", 12, & pointer, "char *", "pointer", pointer,
                    "char", "(char *)((void *)0)", 0);
  count = 0;
  logBlockExit("leak-7-ptr-no-ds.c", 14);
  while (count < 10) {
    logComment("Loop-iteration-start_leak-7-ptr-no-ds.c_14");
    {
    logBlockEntry("leak-7-ptr-no-ds.c", 15);
    tmp = malloc(sizeof(char ) * 256UL);
    logAssignNoOffset("leak-7-ptr-no-ds.c", 15, & tmp, "void *", "tmp", tmp, "void",
                      "malloc", 1);
    logMallocInfo("sizeof(char ) * 256UL", sizeof(char ) * 256UL);
    pointer = (char *)tmp;
    logAssignNoOffset("leak-7-ptr-no-ds.c", 15, & pointer, "char *", "pointer", pointer,
                      "char", "(char *)tmp", 0);
    count ++;
    logBlockExit("leak-7-ptr-no-ds.c", 14);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("", -1);
  logFree("leak-7-ptr-no-ds.c", 18, "(void *)pointer", (void *)pointer);
  free((void *)pointer);
  logBlockExit("leak-7-ptr-no-ds.c", 18);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("pointer", & pointer);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
