/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int item ;
   struct node *next ;
   struct node *prev ;
};
struct dll {
   struct node *head ;
   struct node *tail ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
void insertHead(struct dll *dll , struct node *node ) ;
struct dll *create(void) ;
struct node *node_malloc(int item ) ;
void insertHead(struct dll *dll , struct node *node ) 
{ 


  {
  logComment("Function Entered");
  logVarInScope("formal", "dll", "struct dll *", & dll);
  logVarInScope("formal", "node", "struct node *", & node);
  if ((unsigned long )dll->head == (unsigned long )((void *)0)) {
    if ((unsigned long )dll->tail == (unsigned long )((void *)0)) {
      logBlockEntry("dll_2.c", 23);
      dll->head = node;
      logAssignOffset("dll_2.c", 23, dll, "struct dll", "*dll", & dll->head, "struct node *",
                      "dll->head", dll->head, "struct node", "node", 0);
      dll->tail = node;
      logAssignOffset("dll_2.c", 24, dll, "struct dll", "*dll", & dll->tail, "struct node *",
                      "dll->tail", dll->tail, "struct node", "node", 0);
      logBlockExit("dll_2.c", 24);
    } else {
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
  if ((unsigned long )dll->head != (unsigned long )((void *)0)) {
    if ((unsigned long )dll->tail != (unsigned long )((void *)0)) {
      logBlockEntry("dll_2.c", 26);
      node->next = dll->head;
      logAssignOffset("dll_2.c", 26, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "dll->head", 0);
      (dll->head)->prev = node;
      logAssignOffset("dll_2.c", 27, dll->head, "struct node", "*(dll->head)", & (dll->head)->prev,
                      "struct node *", "(dll->head)->prev", (dll->head)->prev, "struct node",
                      "node", 0);
      dll->head = node;
      logAssignOffset("dll_2.c", 28, dll, "struct dll", "*dll", & dll->head, "struct node *",
                      "dll->head", dll->head, "struct node", "node", 0);
      logBlockExit("dll_2.c", 28);
    } else {
      abort();
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    }
  } else {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("node", & node);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
struct dll *create(void) 
{ 
  struct dll *dll ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "dll", "struct dll *", & dll);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_2.c", 36);
  tmp = malloc(sizeof(struct dll ));
  logAssignNoOffset("dll_2.c", 36, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct dll )", sizeof(struct dll ));
  dll = (struct dll *)tmp;
  logAssignNoOffset("dll_2.c", 36, & dll, "struct dll *", "dll", dll, "struct dll",
                    "(struct dll *)tmp", 0);
  logBlockExit("dll_2.c", 36);
  if ((unsigned long )dll == (unsigned long )((void *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_2.c", 38);
  dll->head = (struct node *)((void *)0);
  logAssignOffset("dll_2.c", 38, dll, "struct dll", "*dll", & dll->head, "struct node *",
                  "dll->head", dll->head, "struct node", "(struct node *)((void *)0)",
                  0);
  dll->tail = (struct node *)((void *)0);
  logAssignOffset("dll_2.c", 39, dll, "struct dll", "*dll", & dll->tail, "struct node *",
                  "dll->tail", dll->tail, "struct node", "(struct node *)((void *)0)",
                  0);
  logBlockExit("dll_2.c", 39);
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (dll);
  }
  }
}
}
struct node *node_malloc(int item ) 
{ 
  struct node *node ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "node", "struct node *", & node);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_2.c", 45);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("dll_2.c", 45, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  node = (struct node *)tmp;
  logAssignNoOffset("dll_2.c", 45, & node, "struct node *", "node", node, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("dll_2.c", 45);
  if ((unsigned long )node == (unsigned long )((struct node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_2.c", 47);
  node->next = (struct node *)0;
  logAssignOffset("dll_2.c", 47, node, "struct node", "*node", & node->next, "struct node *",
                  "node->next", node->next, "struct node", "(struct node *)0", 0);
  node->prev = (struct node *)0;
  logAssignOffset("dll_2.c", 48, node, "struct node", "*node", & node->prev, "struct node *",
                  "node->prev", node->prev, "struct node", "(struct node *)0", 0);
  node->item = item;
  logBlockExit("dll_2.c", 49);
  {
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (node);
  }
  }
}
}
int main(void) 
{ 
  struct dll *dll ;
  struct dll *tmp ;
  struct node *n1 ;
  struct node *tmp___0 ;
  struct node *n2 ;
  struct node *tmp___1 ;
  struct node *n3 ;
  struct node *tmp___2 ;
  struct node *n4 ;
  struct node *tmp___3 ;
  struct node *n5 ;
  struct node *tmp___4 ;

  {
  logComment("Function Entered");
  logVarInScope("local", "dll", "struct dll *", & dll);
  logVarInScope("local", "tmp", "struct dll *", & tmp);
  logVarInScope("local", "n1", "struct node *", & n1);
  logVarInScope("local", "tmp___0", "struct node *", & tmp___0);
  logVarInScope("local", "n2", "struct node *", & n2);
  logVarInScope("local", "tmp___1", "struct node *", & tmp___1);
  logVarInScope("local", "n3", "struct node *", & n3);
  logVarInScope("local", "tmp___2", "struct node *", & tmp___2);
  logVarInScope("local", "n4", "struct node *", & n4);
  logVarInScope("local", "tmp___3", "struct node *", & tmp___3);
  logVarInScope("local", "n5", "struct node *", & n5);
  logVarInScope("local", "tmp___4", "struct node *", & tmp___4);
  tmp = create();
  logBlockEntry("dll_2.c", 57);
  logAssignNoOffset("dll_2.c", 57, & tmp, "struct dll *", "tmp", tmp, "struct dll",
                    "create", 0);
  dumpVarsOutOfScope();
  dll = tmp;
  logAssignNoOffset("dll_2.c", 57, & dll, "struct dll *", "dll", dll, "struct dll",
                    "tmp", 0);
  logBlockExit("dll_2.c", 59);
  tmp___0 = node_malloc(1);
  logBlockEntry("dll_2.c", 59);
  logAssignNoOffset("dll_2.c", 59, & tmp___0, "struct node *", "tmp___0", tmp___0,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n1 = tmp___0;
  logAssignNoOffset("dll_2.c", 59, & n1, "struct node *", "n1", n1, "struct node",
                    "tmp___0", 0);
  logBlockExit("dll_2.c", 60);
  tmp___1 = node_malloc(2);
  logBlockEntry("dll_2.c", 60);
  logAssignNoOffset("dll_2.c", 60, & tmp___1, "struct node *", "tmp___1", tmp___1,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n2 = tmp___1;
  logAssignNoOffset("dll_2.c", 60, & n2, "struct node *", "n2", n2, "struct node",
                    "tmp___1", 0);
  logBlockExit("dll_2.c", 61);
  tmp___2 = node_malloc(3);
  logBlockEntry("dll_2.c", 61);
  logAssignNoOffset("dll_2.c", 61, & tmp___2, "struct node *", "tmp___2", tmp___2,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n3 = tmp___2;
  logAssignNoOffset("dll_2.c", 61, & n3, "struct node *", "n3", n3, "struct node",
                    "tmp___2", 0);
  logBlockExit("dll_2.c", 62);
  tmp___3 = node_malloc(4);
  logBlockEntry("dll_2.c", 62);
  logAssignNoOffset("dll_2.c", 62, & tmp___3, "struct node *", "tmp___3", tmp___3,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n4 = tmp___3;
  logAssignNoOffset("dll_2.c", 62, & n4, "struct node *", "n4", n4, "struct node",
                    "tmp___3", 0);
  logBlockExit("dll_2.c", 63);
  tmp___4 = node_malloc(5);
  logBlockEntry("dll_2.c", 63);
  logAssignNoOffset("dll_2.c", 63, & tmp___4, "struct node *", "tmp___4", tmp___4,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n5 = tmp___4;
  logAssignNoOffset("dll_2.c", 63, & n5, "struct node *", "n5", n5, "struct node",
                    "tmp___4", 0);
  logBlockExit("dll_2.c", 64);
  insertHead(dll, n1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_2.c", 65);
  insertHead(dll, n2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_2.c", 66);
  insertHead(dll, n3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_2.c", 67);
  insertHead(dll, n4);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_2.c", 68);
  insertHead(dll, n5);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("n1", & n1);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("n2", & n2);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("n3", & n3);
  logVarOutOfScope("tmp___2", & tmp___2);
  logVarOutOfScope("n4", & n4);
  logVarOutOfScope("tmp___3", & tmp___3);
  logVarOutOfScope("n5", & n5);
  logVarOutOfScope("tmp___4", & tmp___4);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
