/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int payload ;
   struct node *next ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
struct node *insert(struct node *cur_elem ) 
{ 
  struct node *ret_val ;
  void *tmp ;
  void *tmp___0 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "cur_elem", "struct node *", & cur_elem);
  logVarInScope("local", "ret_val", "struct node *", & ret_val);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logBlockEntry("leak-0-ptr.c", 20);
  ret_val = (struct node *)((void *)0);
  logAssignNoOffset("leak-0-ptr.c", 20, & ret_val, "struct node *", "ret_val", ret_val,
                    "struct node", "(struct node *)((void *)0)", 0);
  logBlockExit("leak-0-ptr.c", 20);
  if ((unsigned long )cur_elem != (unsigned long )((void *)0)) {
    logBlockEntry("leak-0-ptr.c", 22);
    tmp = malloc(sizeof(struct node ));
    logAssignNoOffset("leak-0-ptr.c", 22, & tmp, "void *", "tmp", tmp, "void", "malloc",
                      1);
    logMallocInfo("sizeof(struct node )", sizeof(struct node ));
    cur_elem->next = (struct node *)tmp;
    logAssignOffset("leak-0-ptr.c", 22, cur_elem, "struct node", "*cur_elem", & cur_elem->next,
                    "struct node *", "cur_elem->next", cur_elem->next, "struct node",
                    "(struct node *)tmp", 0);
    logBlockExit("leak-0-ptr.c", 22);
    if ((unsigned long )cur_elem->next == (unsigned long )((void *)0)) {
      printf((char const   * __restrict  )"Error: No space left. Exiting.");
      exit(1);
    }
    logBlockEntry("leak-0-ptr.c", 27);
    (cur_elem->next)->next = (struct node *)((void *)0);
    logAssignOffset("leak-0-ptr.c", 27, cur_elem->next, "struct node", "*(cur_elem->next)",
                    & (cur_elem->next)->next, "struct node *", "(cur_elem->next)->next",
                    (cur_elem->next)->next, "struct node", "(struct node *)((void *)0)",
                    0);
    ret_val = cur_elem->next;
    logAssignNoOffset("leak-0-ptr.c", 28, & ret_val, "struct node *", "ret_val", ret_val,
                      "struct node", "cur_elem->next", 0);
    logBlockExit("leak-0-ptr.c", 28);
  } else {
    logBlockEntry("leak-0-ptr.c", 31);
    tmp___0 = malloc(sizeof(struct node ));
    logAssignNoOffset("leak-0-ptr.c", 31, & tmp___0, "void *", "tmp___0", tmp___0,
                      "void", "malloc", 1);
    logMallocInfo("sizeof(struct node )", sizeof(struct node ));
    cur_elem = (struct node *)tmp___0;
    logAssignNoOffset("leak-0-ptr.c", 31, & cur_elem, "struct node *", "cur_elem",
                      cur_elem, "struct node", "(struct node *)tmp___0", 0);
    logBlockExit("leak-0-ptr.c", 31);
    if ((unsigned long )cur_elem == (unsigned long )((void *)0)) {
      printf((char const   * __restrict  )"Error: No space left. Exiting.");
      exit(1);
    }
    logBlockEntry("leak-0-ptr.c", 36);
    cur_elem->next = (struct node *)((void *)0);
    logAssignOffset("leak-0-ptr.c", 36, cur_elem, "struct node", "*cur_elem", & cur_elem->next,
                    "struct node *", "cur_elem->next", cur_elem->next, "struct node",
                    "(struct node *)((void *)0)", 0);
    ret_val = cur_elem;
    logAssignNoOffset("leak-0-ptr.c", 37, & ret_val, "struct node *", "ret_val", ret_val,
                      "struct node", "cur_elem", 0);
    logBlockExit("leak-0-ptr.c", 37);
  }
  {
  logVarOutOfScope("cur_elem", & cur_elem);
  logVarOutOfScope("ret_val", & ret_val);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  {
  logComment("Function Exited");
  return (ret_val);
  }
  }
}
}
int main(int argc , char **argv ) 
{ 
  struct node *head ;
  struct node *iter ;
  int i ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "head", "struct node *", & head);
  logVarInScope("local", "iter", "struct node *", & iter);
  logBlockEntry("leak-0-ptr.c", 43);
  head = (struct node *)((void *)0);
  logAssignNoOffset("leak-0-ptr.c", 43, & head, "struct node *", "head", head, "struct node",
                    "(struct node *)((void *)0)", 0);
  i = 0;
  logBlockExit("leak-0-ptr.c", 49);
  head = insert(head);
  logBlockEntry("leak-0-ptr.c", 49);
  logAssignNoOffset("leak-0-ptr.c", 49, & head, "struct node *", "head", head, "struct node",
                    "insert", 0);
  dumpVarsOutOfScope();
  iter = head;
  logAssignNoOffset("leak-0-ptr.c", 50, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  iter->payload = i;
  logBlockExit("leak-0-ptr.c", 51);
  while (i < 5) {
    logComment("Loop-iteration-start_leak-0-ptr.c_52");
    {
    printf((char const   * __restrict  )"Inserting element(%d)\n", i);
    iter = insert(iter);
    logBlockEntry("leak-0-ptr.c", 54);
    logAssignNoOffset("leak-0-ptr.c", 54, & iter, "struct node *", "iter", iter, "struct node",
                      "insert", 0);
    dumpVarsOutOfScope();
    iter->payload = i;
    i ++;
    logBlockExit("leak-0-ptr.c", 52);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("leak-0-ptr.c", 59);
  i = 0;
  iter = head;
  logAssignNoOffset("leak-0-ptr.c", 60, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  logBlockExit("leak-0-ptr.c", 60);
  while (i < 3) {
    logComment("Loop-iteration-start_leak-0-ptr.c_61");
    {
    printf((char const   * __restrict  )"Forwarding element(%d)\n", i);
    logBlockEntry("leak-0-ptr.c", 63);
    iter = iter->next;
    logAssignNoOffset("leak-0-ptr.c", 63, & iter, "struct node *", "iter", iter, "struct node",
                      "iter->next", 0);
    i ++;
    logBlockExit("leak-0-ptr.c", 61);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("leak-0-ptr.c", 67);
  iter->next = (struct node *)((void *)0);
  logAssignOffset("leak-0-ptr.c", 67, iter, "struct node", "*iter", & iter->next,
                  "struct node *", "iter->next", iter->next, "struct node", "(struct node *)((void *)0)",
                  0);
  iter = head;
  logAssignNoOffset("leak-0-ptr.c", 70, & iter, "struct node *", "iter", iter, "struct node",
                    "head", 0);
  logBlockExit("leak-0-ptr.c", 70);
  while ((unsigned long )iter != (unsigned long )((void *)0)) {
    logComment("Loop-iteration-start_leak-0-ptr.c_71");
    {
    printf((char const   * __restrict  )"Freeing element\n");
    logBlockEntry("leak-0-ptr.c", 73);
    head = iter->next;
    logAssignNoOffset("leak-0-ptr.c", 73, & head, "struct node *", "head", head, "struct node",
                      "iter->next", 0);
    logFree("leak-0-ptr.c", 74, "(void *)iter", (void *)iter);
    free((void *)iter);
    iter = head;
    logAssignNoOffset("leak-0-ptr.c", 75, & iter, "struct node *", "iter", iter, "struct node",
                      "head", 0);
    logBlockExit("leak-0-ptr.c", 75);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("head", & head);
  logVarOutOfScope("iter", & iter);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
