/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   struct node *next ;
   int value ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
struct node *list_add(struct node *l , int item ) ;
struct node *list_remove(struct node *l ) ;
void list_dispose(struct node *current ) ;
struct node *list_add(struct node *l , int item ) 
{ 
  struct node *new ;
  void *tmp ;
  struct node *n ;
  struct node *head ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct node *", & l);
  logVarInScope("local", "new", "struct node *", & new);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "n", "struct node *", & n);
  logVarInScope("local", "head", "struct node *", & head);
  logBlockEntry("sll_2.c", 16);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("sll_2.c", 16, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  new = (struct node *)tmp;
  logAssignNoOffset("sll_2.c", 16, & new, "struct node *", "new", new, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("sll_2.c", 16);
  if ((unsigned long )new == (unsigned long )((struct node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_2.c", 18);
  new->next = (struct node *)0;
  logAssignOffset("sll_2.c", 18, new, "struct node", "*new", & new->next, "struct node *",
                  "new->next", new->next, "struct node", "(struct node *)0", 0);
  new->value = item;
  logBlockExit("sll_2.c", 19);
  if ((unsigned long )l == (unsigned long )((struct node *)0)) {
    {
    logVarOutOfScope("l", & l);
    logVarOutOfScope("new", & new);
    logVarOutOfScope("tmp", & tmp);
    logVarOutOfScope("n", & n);
    logVarOutOfScope("head", & head);
    {
    logComment("Function Exited");
    return (new);
    }
    }
  } else {
    logBlockEntry("sll_2.c", 24);
    n = l;
    logAssignNoOffset("sll_2.c", 24, & n, "struct node *", "n", n, "struct node",
                      "l", 0);
    head = l;
    logAssignNoOffset("sll_2.c", 25, & head, "struct node *", "head", head, "struct node",
                      "l", 0);
    logBlockExit("sll_2.c", 25);
    while ((unsigned long )n->next != (unsigned long )((struct node *)0)) {
      logComment("Loop-iteration-start_sll_2.c_26");
      {
      logBlockEntry("sll_2.c", 28);
      n = n->next;
      logAssignNoOffset("sll_2.c", 28, & n, "struct node *", "n", n, "struct node",
                        "n->next", 0);
      logBlockExit("sll_2.c", 28);
      }
      logComment("Loop-iteration-end");
    }
    logBlockEntry("sll_2.c", 30);
    n->next = new;
    logAssignOffset("sll_2.c", 30, n, "struct node", "*n", & n->next, "struct node *",
                    "n->next", n->next, "struct node", "new", 0);
    logBlockExit("sll_2.c", 30);
    {
    logVarOutOfScope("l", & l);
    logVarOutOfScope("new", & new);
    logVarOutOfScope("tmp", & tmp);
    logVarOutOfScope("n", & n);
    logVarOutOfScope("head", & head);
    {
    logComment("Function Exited");
    return (head);
    }
    }
  }
}
}
void list_dispose(struct node *current ) 
{ 
  struct node *oldcurrent ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "current", "struct node *", & current);
  logVarInScope("local", "oldcurrent", "struct node *", & oldcurrent);
  while ((unsigned long )current != (unsigned long )((struct node *)0)) {
    logComment("Loop-iteration-start_sll_2.c_37");
    {
    logBlockEntry("sll_2.c", 39);
    oldcurrent = current;
    logAssignNoOffset("sll_2.c", 39, & oldcurrent, "struct node *", "oldcurrent",
                      oldcurrent, "struct node", "current", 0);
    current = current->next;
    logAssignNoOffset("sll_2.c", 40, & current, "struct node *", "current", current,
                      "struct node", "current->next", 0);
    logFree("sll_2.c", 41, "(void *)oldcurrent", (void *)oldcurrent);
    free((void *)oldcurrent);
    logBlockExit("sll_2.c", 41);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("current", & current);
  logVarOutOfScope("oldcurrent", & oldcurrent);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
struct node *list_remove(struct node *l ) 
{ 
  struct node *n ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct node *", & l);
  logVarInScope("local", "n", "struct node *", & n);
  logBlockEntry("sll_2.c", 48);
  n = l;
  logAssignNoOffset("sll_2.c", 48, & n, "struct node *", "n", n, "struct node", "l",
                    0);
  l = l->next;
  logAssignNoOffset("sll_2.c", 49, & l, "struct node *", "l", l, "struct node", "l->next",
                    0);
  logFree("sll_2.c", 50, "(void *)n", (void *)n);
  free((void *)n);
  logBlockExit("sll_2.c", 50);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("n", & n);
  {
  logComment("Function Exited");
  return (l);
  }
  }
}
}
int main(void) 
{ 
  struct node *l ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "struct node *", & l);
  logBlockEntry("sll_2.c", 58);
  l = (struct node *)((void *)0);
  logAssignNoOffset("sll_2.c", 58, & l, "struct node *", "l", l, "struct node", "(struct node *)((void *)0)",
                    0);
  logBlockExit("sll_2.c", 59);
  l = list_add(l, 1);
  logBlockEntry("sll_2.c", 59);
  logAssignNoOffset("sll_2.c", 59, & l, "struct node *", "l", l, "struct node", "list_add",
                    0);
  dumpVarsOutOfScope();
  logBlockExit("sll_2.c", 60);
  l = list_add(l, 2);
  logBlockEntry("sll_2.c", 60);
  logAssignNoOffset("sll_2.c", 60, & l, "struct node *", "l", l, "struct node", "list_add",
                    0);
  dumpVarsOutOfScope();
  logBlockExit("sll_2.c", 61);
  l = list_add(l, 3);
  logBlockEntry("sll_2.c", 61);
  logAssignNoOffset("sll_2.c", 61, & l, "struct node *", "l", l, "struct node", "list_add",
                    0);
  dumpVarsOutOfScope();
  logBlockExit("sll_2.c", 62);
  l = list_remove(l);
  logBlockEntry("sll_2.c", 62);
  logAssignNoOffset("sll_2.c", 62, & l, "struct node *", "l", l, "struct node", "list_remove",
                    0);
  dumpVarsOutOfScope();
  logBlockExit("sll_2.c", 63);
  list_dispose(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("l", & l);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
