/* Generated by CIL v. 1.7.2 */
/* print_CIL_Input is true */

struct voidlink {
   int data ;
   void *next ;
};
typedef struct voidlink voidlink___0;
struct link {
   int data ;
   struct link *next ;
};
typedef struct link link;
struct list_element {
   int payload ;
   voidlink___0 voidlinkage ;
   link linkage ;
};
typedef struct list_element list_element;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
struct voidlink voidlink  ;
int main(int argc , char **argv ) 
{ 
  list_element elem01 ;
  list_element elem02 ;
  list_element elem03 ;
  list_element elem04 ;
  struct voidlink *elem04linkageptr ;
  list_element *elem04ptr ;

  {
  logComment("Function Entered");
  logBlockEntry("cell-resize.c", 32);
  elem01.payload = 1;
  elem02.payload = 2;
  elem01.voidlinkage.next = (void *)(& elem02.voidlinkage);
  logAssignOffset("cell-resize.c", 35, & elem01, "struct list_element", "elem01",
                  & elem01.voidlinkage.next, "void *", "elem01.voidlinkage.next",
                  elem01.voidlinkage.next, "void", "(void *)(& elem02.voidlinkage)",
                  0);
  elem01.voidlinkage.next = (void *)0;
  logAssignOffset("cell-resize.c", 36, & elem01, "struct list_element", "elem01",
                  & elem01.voidlinkage.next, "void *", "elem01.voidlinkage.next",
                  elem01.voidlinkage.next, "void", "(void *)0", 0);
  elem01.voidlinkage.next = (void *)(& elem02);
  logAssignOffset("cell-resize.c", 38, & elem01, "struct list_element", "elem01",
                  & elem01.voidlinkage.next, "void *", "elem01.voidlinkage.next",
                  elem01.voidlinkage.next, "void", "(void *)(& elem02)", 0);
  elem01.linkage.next = & elem02.linkage;
  logAssignOffset("cell-resize.c", 41, & elem01, "struct list_element", "elem01",
                  & elem01.linkage.next, "struct link *", "elem01.linkage.next", elem01.linkage.next,
                  "struct link", "& elem02.linkage", 0);
  elem01.linkage.next = (struct link *)((void *)0);
  logAssignOffset("cell-resize.c", 42, & elem01, "struct list_element", "elem01",
                  & elem01.linkage.next, "struct link *", "elem01.linkage.next", elem01.linkage.next,
                  "struct link", "(struct link *)((void *)0)", 0);
  elem04linkageptr = & elem04.voidlinkage;
  logAssignNoOffset("cell-resize.c", 44, & elem04linkageptr, "struct voidlink *",
                    "elem04linkageptr", elem04linkageptr, "struct voidlink", "& elem04.voidlinkage",
                    0);
  elem03.voidlinkage.next = (void *)elem04linkageptr;
  logAssignOffset("cell-resize.c", 45, & elem03, "struct list_element", "elem03",
                  & elem03.voidlinkage.next, "void *", "elem03.voidlinkage.next",
                  elem03.voidlinkage.next, "void", "(void *)elem04linkageptr", 0);
  elem04ptr = & elem04;
  logAssignNoOffset("cell-resize.c", 46, & elem04ptr, "struct list_element *", "elem04ptr",
                    elem04ptr, "struct list_element", "& elem04", 0);
  elem03.voidlinkage.next = (void *)elem04ptr;
  logAssignOffset("cell-resize.c", 47, & elem03, "struct list_element", "elem03",
                  & elem03.voidlinkage.next, "void *", "elem03.voidlinkage.next",
                  elem03.voidlinkage.next, "void", "(void *)elem04ptr", 0);
  logBlockExit("cell-resize.c", 47);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("elem01", & elem01);
  logVarOutOfScope("elem02", & elem02);
  logVarOutOfScope("elem03", & elem03);
  logVarOutOfScope("elem04", & elem04);
  logVarOutOfScope("elem04linkageptr", & elem04linkageptr);
  logVarOutOfScope("elem04ptr", & elem04ptr);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
