/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct type_1 {
   void *next ;
};
struct type_2 {
   void *next ;
};
struct type_3 {
   void *next ;
};
struct type_4 {
   void *next ;
};
struct type_5 {
   void *next ;
};
struct type_6 {
   void *next ;
};
struct type_7 {
   void *next ;
};
struct type_8 {
   void *next ;
};
struct type_9 {
   void *next ;
};
struct type_10 {
   void *next ;
};
struct type_11 {
   void *next ;
};
struct type_12 {
   void *next ;
};
struct type_13 {
   void *next ;
};
struct type_14 {
   void *next ;
};
struct type_15 {
   void *next ;
};
struct type_16 {
   void *next ;
};
struct type_17 {
   void *next ;
};
struct type_18 {
   void *next ;
};
struct type_19 {
   void *next ;
};
struct type_20 {
   void *next ;
};
struct type_21 {
   void *next ;
};
struct type_22 {
   void *next ;
};
struct type_23 {
   void *next ;
};
struct type_24 {
   void *next ;
};
struct type_25 {
   void *next ;
};
struct type_26 {
   void *next ;
};
struct type_27 {
   void *next ;
};
struct type_28 {
   void *next ;
};
struct type_29 {
   void *next ;
};
struct type_30 {
   void *next ;
};
struct type_31 {
   void *next ;
};
struct type_32 {
   void *next ;
};
struct type_33 {
   void *next ;
};
struct type_34 {
   void *next ;
};
struct type_35 {
   void *next ;
};
struct type_36 {
   void *next ;
};
struct type_37 {
   void *next ;
};
struct type_38 {
   void *next ;
};
struct type_39 {
   void *next ;
};
struct type_40 {
   void *next ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
int main(int argc , char **argv ) 
{ 
  struct type_1 head ;
  void *last_elem ;
  int i ;
  struct type_1 *first ;
  void *tmp ;
  struct type_1 *second ;
  void *tmp___0 ;
  struct type_2 *first___0 ;
  void *tmp___1 ;
  struct type_2 *second___0 ;
  void *tmp___2 ;
  struct type_3 *first___1 ;
  void *tmp___3 ;
  struct type_3 *second___1 ;
  void *tmp___4 ;
  struct type_4 *first___2 ;
  void *tmp___5 ;
  struct type_4 *second___2 ;
  void *tmp___6 ;
  struct type_5 *first___3 ;
  void *tmp___7 ;
  struct type_5 *second___3 ;
  void *tmp___8 ;
  struct type_6 *first___4 ;
  void *tmp___9 ;
  struct type_6 *second___4 ;
  void *tmp___10 ;
  struct type_7 *first___5 ;
  void *tmp___11 ;
  struct type_7 *second___5 ;
  void *tmp___12 ;
  struct type_8 *first___6 ;
  void *tmp___13 ;
  struct type_8 *second___6 ;
  void *tmp___14 ;
  struct type_9 *first___7 ;
  void *tmp___15 ;
  struct type_9 *second___7 ;
  void *tmp___16 ;
  struct type_10 *first___8 ;
  void *tmp___17 ;
  struct type_10 *second___8 ;
  void *tmp___18 ;
  struct type_11 *first___9 ;
  void *tmp___19 ;
  struct type_11 *second___9 ;
  void *tmp___20 ;
  struct type_12 *first___10 ;
  void *tmp___21 ;
  struct type_12 *second___10 ;
  void *tmp___22 ;
  struct type_13 *first___11 ;
  void *tmp___23 ;
  struct type_13 *second___11 ;
  void *tmp___24 ;
  struct type_14 *first___12 ;
  void *tmp___25 ;
  struct type_14 *second___12 ;
  void *tmp___26 ;
  struct type_15 *first___13 ;
  void *tmp___27 ;
  struct type_15 *second___13 ;
  void *tmp___28 ;
  struct type_16 *first___14 ;
  void *tmp___29 ;
  struct type_16 *second___14 ;
  void *tmp___30 ;
  struct type_17 *first___15 ;
  void *tmp___31 ;
  struct type_17 *second___15 ;
  void *tmp___32 ;
  struct type_18 *first___16 ;
  void *tmp___33 ;
  struct type_18 *second___16 ;
  void *tmp___34 ;
  struct type_19 *first___17 ;
  void *tmp___35 ;
  struct type_19 *second___17 ;
  void *tmp___36 ;
  struct type_20 *first___18 ;
  void *tmp___37 ;
  struct type_20 *second___18 ;
  void *tmp___38 ;
  struct type_21 *first___19 ;
  void *tmp___39 ;
  struct type_21 *second___19 ;
  void *tmp___40 ;
  struct type_22 *first___20 ;
  void *tmp___41 ;
  struct type_22 *second___20 ;
  void *tmp___42 ;
  struct type_23 *first___21 ;
  void *tmp___43 ;
  struct type_23 *second___21 ;
  void *tmp___44 ;
  struct type_24 *first___22 ;
  void *tmp___45 ;
  struct type_24 *second___22 ;
  void *tmp___46 ;
  struct type_25 *first___23 ;
  void *tmp___47 ;
  struct type_25 *second___23 ;
  void *tmp___48 ;
  struct type_26 *first___24 ;
  void *tmp___49 ;
  struct type_26 *second___24 ;
  void *tmp___50 ;
  struct type_27 *first___25 ;
  void *tmp___51 ;
  struct type_27 *second___25 ;
  void *tmp___52 ;
  struct type_28 *first___26 ;
  void *tmp___53 ;
  struct type_28 *second___26 ;
  void *tmp___54 ;
  struct type_29 *first___27 ;
  void *tmp___55 ;
  struct type_29 *second___27 ;
  void *tmp___56 ;
  struct type_30 *first___28 ;
  void *tmp___57 ;
  struct type_30 *second___28 ;
  void *tmp___58 ;
  struct type_31 *first___29 ;
  void *tmp___59 ;
  struct type_31 *second___29 ;
  void *tmp___60 ;
  struct type_32 *first___30 ;
  void *tmp___61 ;
  struct type_32 *second___30 ;
  void *tmp___62 ;
  struct type_33 *first___31 ;
  void *tmp___63 ;
  struct type_33 *second___31 ;
  void *tmp___64 ;
  struct type_34 *first___32 ;
  void *tmp___65 ;
  struct type_34 *second___32 ;
  void *tmp___66 ;
  struct type_35 *first___33 ;
  void *tmp___67 ;
  struct type_35 *second___33 ;
  void *tmp___68 ;
  struct type_36 *first___34 ;
  void *tmp___69 ;
  struct type_36 *second___34 ;
  void *tmp___70 ;
  struct type_37 *first___35 ;
  void *tmp___71 ;
  struct type_37 *second___35 ;
  void *tmp___72 ;
  struct type_38 *first___36 ;
  void *tmp___73 ;
  struct type_38 *second___36 ;
  void *tmp___74 ;
  struct type_39 *first___37 ;
  void *tmp___75 ;
  struct type_39 *second___37 ;
  void *tmp___76 ;
  struct type_40 *first___38 ;
  void *tmp___77 ;
  struct type_40 *second___38 ;
  void *tmp___78 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "head", "struct type_1", & head);
  logVarInScope("local", "last_elem", "void *", & last_elem);
  logVarInScope("local", "first", "struct type_1 *", & first);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "second", "struct type_1 *", & second);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logVarInScope("local", "first___0", "struct type_2 *", & first___0);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logVarInScope("local", "second___0", "struct type_2 *", & second___0);
  logVarInScope("local", "tmp___2", "void *", & tmp___2);
  logVarInScope("local", "first___1", "struct type_3 *", & first___1);
  logVarInScope("local", "tmp___3", "void *", & tmp___3);
  logVarInScope("local", "second___1", "struct type_3 *", & second___1);
  logVarInScope("local", "tmp___4", "void *", & tmp___4);
  logVarInScope("local", "first___2", "struct type_4 *", & first___2);
  logVarInScope("local", "tmp___5", "void *", & tmp___5);
  logVarInScope("local", "second___2", "struct type_4 *", & second___2);
  logVarInScope("local", "tmp___6", "void *", & tmp___6);
  logVarInScope("local", "first___3", "struct type_5 *", & first___3);
  logVarInScope("local", "tmp___7", "void *", & tmp___7);
  logVarInScope("local", "second___3", "struct type_5 *", & second___3);
  logVarInScope("local", "tmp___8", "void *", & tmp___8);
  logVarInScope("local", "first___4", "struct type_6 *", & first___4);
  logVarInScope("local", "tmp___9", "void *", & tmp___9);
  logVarInScope("local", "second___4", "struct type_6 *", & second___4);
  logVarInScope("local", "tmp___10", "void *", & tmp___10);
  logVarInScope("local", "first___5", "struct type_7 *", & first___5);
  logVarInScope("local", "tmp___11", "void *", & tmp___11);
  logVarInScope("local", "second___5", "struct type_7 *", & second___5);
  logVarInScope("local", "tmp___12", "void *", & tmp___12);
  logVarInScope("local", "first___6", "struct type_8 *", & first___6);
  logVarInScope("local", "tmp___13", "void *", & tmp___13);
  logVarInScope("local", "second___6", "struct type_8 *", & second___6);
  logVarInScope("local", "tmp___14", "void *", & tmp___14);
  logVarInScope("local", "first___7", "struct type_9 *", & first___7);
  logVarInScope("local", "tmp___15", "void *", & tmp___15);
  logVarInScope("local", "second___7", "struct type_9 *", & second___7);
  logVarInScope("local", "tmp___16", "void *", & tmp___16);
  logVarInScope("local", "first___8", "struct type_10 *", & first___8);
  logVarInScope("local", "tmp___17", "void *", & tmp___17);
  logVarInScope("local", "second___8", "struct type_10 *", & second___8);
  logVarInScope("local", "tmp___18", "void *", & tmp___18);
  logVarInScope("local", "first___9", "struct type_11 *", & first___9);
  logVarInScope("local", "tmp___19", "void *", & tmp___19);
  logVarInScope("local", "second___9", "struct type_11 *", & second___9);
  logVarInScope("local", "tmp___20", "void *", & tmp___20);
  logVarInScope("local", "first___10", "struct type_12 *", & first___10);
  logVarInScope("local", "tmp___21", "void *", & tmp___21);
  logVarInScope("local", "second___10", "struct type_12 *", & second___10);
  logVarInScope("local", "tmp___22", "void *", & tmp___22);
  logVarInScope("local", "first___11", "struct type_13 *", & first___11);
  logVarInScope("local", "tmp___23", "void *", & tmp___23);
  logVarInScope("local", "second___11", "struct type_13 *", & second___11);
  logVarInScope("local", "tmp___24", "void *", & tmp___24);
  logVarInScope("local", "first___12", "struct type_14 *", & first___12);
  logVarInScope("local", "tmp___25", "void *", & tmp___25);
  logVarInScope("local", "second___12", "struct type_14 *", & second___12);
  logVarInScope("local", "tmp___26", "void *", & tmp___26);
  logVarInScope("local", "first___13", "struct type_15 *", & first___13);
  logVarInScope("local", "tmp___27", "void *", & tmp___27);
  logVarInScope("local", "second___13", "struct type_15 *", & second___13);
  logVarInScope("local", "tmp___28", "void *", & tmp___28);
  logVarInScope("local", "first___14", "struct type_16 *", & first___14);
  logVarInScope("local", "tmp___29", "void *", & tmp___29);
  logVarInScope("local", "second___14", "struct type_16 *", & second___14);
  logVarInScope("local", "tmp___30", "void *", & tmp___30);
  logVarInScope("local", "first___15", "struct type_17 *", & first___15);
  logVarInScope("local", "tmp___31", "void *", & tmp___31);
  logVarInScope("local", "second___15", "struct type_17 *", & second___15);
  logVarInScope("local", "tmp___32", "void *", & tmp___32);
  logVarInScope("local", "first___16", "struct type_18 *", & first___16);
  logVarInScope("local", "tmp___33", "void *", & tmp___33);
  logVarInScope("local", "second___16", "struct type_18 *", & second___16);
  logVarInScope("local", "tmp___34", "void *", & tmp___34);
  logVarInScope("local", "first___17", "struct type_19 *", & first___17);
  logVarInScope("local", "tmp___35", "void *", & tmp___35);
  logVarInScope("local", "second___17", "struct type_19 *", & second___17);
  logVarInScope("local", "tmp___36", "void *", & tmp___36);
  logVarInScope("local", "first___18", "struct type_20 *", & first___18);
  logVarInScope("local", "tmp___37", "void *", & tmp___37);
  logVarInScope("local", "second___18", "struct type_20 *", & second___18);
  logVarInScope("local", "tmp___38", "void *", & tmp___38);
  logVarInScope("local", "first___19", "struct type_21 *", & first___19);
  logVarInScope("local", "tmp___39", "void *", & tmp___39);
  logVarInScope("local", "second___19", "struct type_21 *", & second___19);
  logVarInScope("local", "tmp___40", "void *", & tmp___40);
  logVarInScope("local", "first___20", "struct type_22 *", & first___20);
  logVarInScope("local", "tmp___41", "void *", & tmp___41);
  logVarInScope("local", "second___20", "struct type_22 *", & second___20);
  logVarInScope("local", "tmp___42", "void *", & tmp___42);
  logVarInScope("local", "first___21", "struct type_23 *", & first___21);
  logVarInScope("local", "tmp___43", "void *", & tmp___43);
  logVarInScope("local", "second___21", "struct type_23 *", & second___21);
  logVarInScope("local", "tmp___44", "void *", & tmp___44);
  logVarInScope("local", "first___22", "struct type_24 *", & first___22);
  logVarInScope("local", "tmp___45", "void *", & tmp___45);
  logVarInScope("local", "second___22", "struct type_24 *", & second___22);
  logVarInScope("local", "tmp___46", "void *", & tmp___46);
  logVarInScope("local", "first___23", "struct type_25 *", & first___23);
  logVarInScope("local", "tmp___47", "void *", & tmp___47);
  logVarInScope("local", "second___23", "struct type_25 *", & second___23);
  logVarInScope("local", "tmp___48", "void *", & tmp___48);
  logVarInScope("local", "first___24", "struct type_26 *", & first___24);
  logVarInScope("local", "tmp___49", "void *", & tmp___49);
  logVarInScope("local", "second___24", "struct type_26 *", & second___24);
  logVarInScope("local", "tmp___50", "void *", & tmp___50);
  logVarInScope("local", "first___25", "struct type_27 *", & first___25);
  logVarInScope("local", "tmp___51", "void *", & tmp___51);
  logVarInScope("local", "second___25", "struct type_27 *", & second___25);
  logVarInScope("local", "tmp___52", "void *", & tmp___52);
  logVarInScope("local", "first___26", "struct type_28 *", & first___26);
  logVarInScope("local", "tmp___53", "void *", & tmp___53);
  logVarInScope("local", "second___26", "struct type_28 *", & second___26);
  logVarInScope("local", "tmp___54", "void *", & tmp___54);
  logVarInScope("local", "first___27", "struct type_29 *", & first___27);
  logVarInScope("local", "tmp___55", "void *", & tmp___55);
  logVarInScope("local", "second___27", "struct type_29 *", & second___27);
  logVarInScope("local", "tmp___56", "void *", & tmp___56);
  logVarInScope("local", "first___28", "struct type_30 *", & first___28);
  logVarInScope("local", "tmp___57", "void *", & tmp___57);
  logVarInScope("local", "second___28", "struct type_30 *", & second___28);
  logVarInScope("local", "tmp___58", "void *", & tmp___58);
  logVarInScope("local", "first___29", "struct type_31 *", & first___29);
  logVarInScope("local", "tmp___59", "void *", & tmp___59);
  logVarInScope("local", "second___29", "struct type_31 *", & second___29);
  logVarInScope("local", "tmp___60", "void *", & tmp___60);
  logVarInScope("local", "first___30", "struct type_32 *", & first___30);
  logVarInScope("local", "tmp___61", "void *", & tmp___61);
  logVarInScope("local", "second___30", "struct type_32 *", & second___30);
  logVarInScope("local", "tmp___62", "void *", & tmp___62);
  logVarInScope("local", "first___31", "struct type_33 *", & first___31);
  logVarInScope("local", "tmp___63", "void *", & tmp___63);
  logVarInScope("local", "second___31", "struct type_33 *", & second___31);
  logVarInScope("local", "tmp___64", "void *", & tmp___64);
  logVarInScope("local", "first___32", "struct type_34 *", & first___32);
  logVarInScope("local", "tmp___65", "void *", & tmp___65);
  logVarInScope("local", "second___32", "struct type_34 *", & second___32);
  logVarInScope("local", "tmp___66", "void *", & tmp___66);
  logVarInScope("local", "first___33", "struct type_35 *", & first___33);
  logVarInScope("local", "tmp___67", "void *", & tmp___67);
  logVarInScope("local", "second___33", "struct type_35 *", & second___33);
  logVarInScope("local", "tmp___68", "void *", & tmp___68);
  logVarInScope("local", "first___34", "struct type_36 *", & first___34);
  logVarInScope("local", "tmp___69", "void *", & tmp___69);
  logVarInScope("local", "second___34", "struct type_36 *", & second___34);
  logVarInScope("local", "tmp___70", "void *", & tmp___70);
  logVarInScope("local", "first___35", "struct type_37 *", & first___35);
  logVarInScope("local", "tmp___71", "void *", & tmp___71);
  logVarInScope("local", "second___35", "struct type_37 *", & second___35);
  logVarInScope("local", "tmp___72", "void *", & tmp___72);
  logVarInScope("local", "first___36", "struct type_38 *", & first___36);
  logVarInScope("local", "tmp___73", "void *", & tmp___73);
  logVarInScope("local", "second___36", "struct type_38 *", & second___36);
  logVarInScope("local", "tmp___74", "void *", & tmp___74);
  logVarInScope("local", "first___37", "struct type_39 *", & first___37);
  logVarInScope("local", "tmp___75", "void *", & tmp___75);
  logVarInScope("local", "second___37", "struct type_39 *", & second___37);
  logVarInScope("local", "tmp___76", "void *", & tmp___76);
  logVarInScope("local", "first___38", "struct type_40 *", & first___38);
  logVarInScope("local", "tmp___77", "void *", & tmp___77);
  logVarInScope("local", "second___38", "struct type_40 *", & second___38);
  logVarInScope("local", "tmp___78", "void *", & tmp___78);
  logBlockEntry("heterogeneous-sg.c", 136);
  last_elem = (void *)(& head);
  logAssignNoOffset("heterogeneous-sg.c", 136, & last_elem, "void *", "last_elem",
                    last_elem, "void", "(void *)(& head)", 0);
  i = 0;
  tmp = malloc(sizeof(struct type_1 ));
  logAssignNoOffset("heterogeneous-sg.c", 138, & tmp, "void *", "tmp", tmp, "void",
                    "malloc", 1);
  logMallocInfo("sizeof(struct type_1 )", sizeof(struct type_1 ));
  first = (struct type_1 *)tmp;
  logAssignNoOffset("heterogeneous-sg.c", 138, & first, "struct type_1 *", "first",
                    first, "struct type_1", "(struct type_1 *)tmp", 0);
  tmp___0 = malloc(sizeof(struct type_1 ));
  logAssignNoOffset("heterogeneous-sg.c", 138, & tmp___0, "void *", "tmp___0", tmp___0,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_1 )", sizeof(struct type_1 ));
  second = (struct type_1 *)tmp___0;
  logAssignNoOffset("heterogeneous-sg.c", 138, & second, "struct type_1 *", "second",
                    second, "struct type_1", "(struct type_1 *)tmp___0", 0);
  first->next = (void *)second;
  logAssignOffset("heterogeneous-sg.c", 138, first, "struct type_1", "*first", & first->next,
                  "void *", "first->next", first->next, "void", "(void *)second",
                  0);
  tmp___1 = malloc(sizeof(struct type_2 ));
  logAssignNoOffset("heterogeneous-sg.c", 139, & tmp___1, "void *", "tmp___1", tmp___1,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_2 )", sizeof(struct type_2 ));
  first___0 = (struct type_2 *)tmp___1;
  logAssignNoOffset("heterogeneous-sg.c", 139, & first___0, "struct type_2 *", "first___0",
                    first___0, "struct type_2", "(struct type_2 *)tmp___1", 0);
  tmp___2 = malloc(sizeof(struct type_2 ));
  logAssignNoOffset("heterogeneous-sg.c", 139, & tmp___2, "void *", "tmp___2", tmp___2,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_2 )", sizeof(struct type_2 ));
  second___0 = (struct type_2 *)tmp___2;
  logAssignNoOffset("heterogeneous-sg.c", 139, & second___0, "struct type_2 *", "second___0",
                    second___0, "struct type_2", "(struct type_2 *)tmp___2", 0);
  first___0->next = (void *)second___0;
  logAssignOffset("heterogeneous-sg.c", 139, first___0, "struct type_2", "*first___0",
                  & first___0->next, "void *", "first___0->next", first___0->next,
                  "void", "(void *)second___0", 0);
  tmp___3 = malloc(sizeof(struct type_3 ));
  logAssignNoOffset("heterogeneous-sg.c", 140, & tmp___3, "void *", "tmp___3", tmp___3,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_3 )", sizeof(struct type_3 ));
  first___1 = (struct type_3 *)tmp___3;
  logAssignNoOffset("heterogeneous-sg.c", 140, & first___1, "struct type_3 *", "first___1",
                    first___1, "struct type_3", "(struct type_3 *)tmp___3", 0);
  tmp___4 = malloc(sizeof(struct type_3 ));
  logAssignNoOffset("heterogeneous-sg.c", 140, & tmp___4, "void *", "tmp___4", tmp___4,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_3 )", sizeof(struct type_3 ));
  second___1 = (struct type_3 *)tmp___4;
  logAssignNoOffset("heterogeneous-sg.c", 140, & second___1, "struct type_3 *", "second___1",
                    second___1, "struct type_3", "(struct type_3 *)tmp___4", 0);
  first___1->next = (void *)second___1;
  logAssignOffset("heterogeneous-sg.c", 140, first___1, "struct type_3", "*first___1",
                  & first___1->next, "void *", "first___1->next", first___1->next,
                  "void", "(void *)second___1", 0);
  tmp___5 = malloc(sizeof(struct type_4 ));
  logAssignNoOffset("heterogeneous-sg.c", 141, & tmp___5, "void *", "tmp___5", tmp___5,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_4 )", sizeof(struct type_4 ));
  first___2 = (struct type_4 *)tmp___5;
  logAssignNoOffset("heterogeneous-sg.c", 141, & first___2, "struct type_4 *", "first___2",
                    first___2, "struct type_4", "(struct type_4 *)tmp___5", 0);
  tmp___6 = malloc(sizeof(struct type_4 ));
  logAssignNoOffset("heterogeneous-sg.c", 141, & tmp___6, "void *", "tmp___6", tmp___6,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_4 )", sizeof(struct type_4 ));
  second___2 = (struct type_4 *)tmp___6;
  logAssignNoOffset("heterogeneous-sg.c", 141, & second___2, "struct type_4 *", "second___2",
                    second___2, "struct type_4", "(struct type_4 *)tmp___6", 0);
  first___2->next = (void *)second___2;
  logAssignOffset("heterogeneous-sg.c", 141, first___2, "struct type_4", "*first___2",
                  & first___2->next, "void *", "first___2->next", first___2->next,
                  "void", "(void *)second___2", 0);
  tmp___7 = malloc(sizeof(struct type_5 ));
  logAssignNoOffset("heterogeneous-sg.c", 142, & tmp___7, "void *", "tmp___7", tmp___7,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_5 )", sizeof(struct type_5 ));
  first___3 = (struct type_5 *)tmp___7;
  logAssignNoOffset("heterogeneous-sg.c", 142, & first___3, "struct type_5 *", "first___3",
                    first___3, "struct type_5", "(struct type_5 *)tmp___7", 0);
  tmp___8 = malloc(sizeof(struct type_5 ));
  logAssignNoOffset("heterogeneous-sg.c", 142, & tmp___8, "void *", "tmp___8", tmp___8,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_5 )", sizeof(struct type_5 ));
  second___3 = (struct type_5 *)tmp___8;
  logAssignNoOffset("heterogeneous-sg.c", 142, & second___3, "struct type_5 *", "second___3",
                    second___3, "struct type_5", "(struct type_5 *)tmp___8", 0);
  first___3->next = (void *)second___3;
  logAssignOffset("heterogeneous-sg.c", 142, first___3, "struct type_5", "*first___3",
                  & first___3->next, "void *", "first___3->next", first___3->next,
                  "void", "(void *)second___3", 0);
  tmp___9 = malloc(sizeof(struct type_6 ));
  logAssignNoOffset("heterogeneous-sg.c", 143, & tmp___9, "void *", "tmp___9", tmp___9,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_6 )", sizeof(struct type_6 ));
  first___4 = (struct type_6 *)tmp___9;
  logAssignNoOffset("heterogeneous-sg.c", 143, & first___4, "struct type_6 *", "first___4",
                    first___4, "struct type_6", "(struct type_6 *)tmp___9", 0);
  tmp___10 = malloc(sizeof(struct type_6 ));
  logAssignNoOffset("heterogeneous-sg.c", 143, & tmp___10, "void *", "tmp___10", tmp___10,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_6 )", sizeof(struct type_6 ));
  second___4 = (struct type_6 *)tmp___10;
  logAssignNoOffset("heterogeneous-sg.c", 143, & second___4, "struct type_6 *", "second___4",
                    second___4, "struct type_6", "(struct type_6 *)tmp___10", 0);
  first___4->next = (void *)second___4;
  logAssignOffset("heterogeneous-sg.c", 143, first___4, "struct type_6", "*first___4",
                  & first___4->next, "void *", "first___4->next", first___4->next,
                  "void", "(void *)second___4", 0);
  tmp___11 = malloc(sizeof(struct type_7 ));
  logAssignNoOffset("heterogeneous-sg.c", 144, & tmp___11, "void *", "tmp___11", tmp___11,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_7 )", sizeof(struct type_7 ));
  first___5 = (struct type_7 *)tmp___11;
  logAssignNoOffset("heterogeneous-sg.c", 144, & first___5, "struct type_7 *", "first___5",
                    first___5, "struct type_7", "(struct type_7 *)tmp___11", 0);
  tmp___12 = malloc(sizeof(struct type_7 ));
  logAssignNoOffset("heterogeneous-sg.c", 144, & tmp___12, "void *", "tmp___12", tmp___12,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_7 )", sizeof(struct type_7 ));
  second___5 = (struct type_7 *)tmp___12;
  logAssignNoOffset("heterogeneous-sg.c", 144, & second___5, "struct type_7 *", "second___5",
                    second___5, "struct type_7", "(struct type_7 *)tmp___12", 0);
  first___5->next = (void *)second___5;
  logAssignOffset("heterogeneous-sg.c", 144, first___5, "struct type_7", "*first___5",
                  & first___5->next, "void *", "first___5->next", first___5->next,
                  "void", "(void *)second___5", 0);
  tmp___13 = malloc(sizeof(struct type_8 ));
  logAssignNoOffset("heterogeneous-sg.c", 145, & tmp___13, "void *", "tmp___13", tmp___13,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_8 )", sizeof(struct type_8 ));
  first___6 = (struct type_8 *)tmp___13;
  logAssignNoOffset("heterogeneous-sg.c", 145, & first___6, "struct type_8 *", "first___6",
                    first___6, "struct type_8", "(struct type_8 *)tmp___13", 0);
  tmp___14 = malloc(sizeof(struct type_8 ));
  logAssignNoOffset("heterogeneous-sg.c", 145, & tmp___14, "void *", "tmp___14", tmp___14,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_8 )", sizeof(struct type_8 ));
  second___6 = (struct type_8 *)tmp___14;
  logAssignNoOffset("heterogeneous-sg.c", 145, & second___6, "struct type_8 *", "second___6",
                    second___6, "struct type_8", "(struct type_8 *)tmp___14", 0);
  first___6->next = (void *)second___6;
  logAssignOffset("heterogeneous-sg.c", 145, first___6, "struct type_8", "*first___6",
                  & first___6->next, "void *", "first___6->next", first___6->next,
                  "void", "(void *)second___6", 0);
  tmp___15 = malloc(sizeof(struct type_9 ));
  logAssignNoOffset("heterogeneous-sg.c", 146, & tmp___15, "void *", "tmp___15", tmp___15,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_9 )", sizeof(struct type_9 ));
  first___7 = (struct type_9 *)tmp___15;
  logAssignNoOffset("heterogeneous-sg.c", 146, & first___7, "struct type_9 *", "first___7",
                    first___7, "struct type_9", "(struct type_9 *)tmp___15", 0);
  tmp___16 = malloc(sizeof(struct type_9 ));
  logAssignNoOffset("heterogeneous-sg.c", 146, & tmp___16, "void *", "tmp___16", tmp___16,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_9 )", sizeof(struct type_9 ));
  second___7 = (struct type_9 *)tmp___16;
  logAssignNoOffset("heterogeneous-sg.c", 146, & second___7, "struct type_9 *", "second___7",
                    second___7, "struct type_9", "(struct type_9 *)tmp___16", 0);
  first___7->next = (void *)second___7;
  logAssignOffset("heterogeneous-sg.c", 146, first___7, "struct type_9", "*first___7",
                  & first___7->next, "void *", "first___7->next", first___7->next,
                  "void", "(void *)second___7", 0);
  tmp___17 = malloc(sizeof(struct type_10 ));
  logAssignNoOffset("heterogeneous-sg.c", 147, & tmp___17, "void *", "tmp___17", tmp___17,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_10 )", sizeof(struct type_10 ));
  first___8 = (struct type_10 *)tmp___17;
  logAssignNoOffset("heterogeneous-sg.c", 147, & first___8, "struct type_10 *", "first___8",
                    first___8, "struct type_10", "(struct type_10 *)tmp___17", 0);
  tmp___18 = malloc(sizeof(struct type_10 ));
  logAssignNoOffset("heterogeneous-sg.c", 147, & tmp___18, "void *", "tmp___18", tmp___18,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_10 )", sizeof(struct type_10 ));
  second___8 = (struct type_10 *)tmp___18;
  logAssignNoOffset("heterogeneous-sg.c", 147, & second___8, "struct type_10 *", "second___8",
                    second___8, "struct type_10", "(struct type_10 *)tmp___18", 0);
  first___8->next = (void *)second___8;
  logAssignOffset("heterogeneous-sg.c", 147, first___8, "struct type_10", "*first___8",
                  & first___8->next, "void *", "first___8->next", first___8->next,
                  "void", "(void *)second___8", 0);
  tmp___19 = malloc(sizeof(struct type_11 ));
  logAssignNoOffset("heterogeneous-sg.c", 148, & tmp___19, "void *", "tmp___19", tmp___19,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_11 )", sizeof(struct type_11 ));
  first___9 = (struct type_11 *)tmp___19;
  logAssignNoOffset("heterogeneous-sg.c", 148, & first___9, "struct type_11 *", "first___9",
                    first___9, "struct type_11", "(struct type_11 *)tmp___19", 0);
  tmp___20 = malloc(sizeof(struct type_11 ));
  logAssignNoOffset("heterogeneous-sg.c", 148, & tmp___20, "void *", "tmp___20", tmp___20,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_11 )", sizeof(struct type_11 ));
  second___9 = (struct type_11 *)tmp___20;
  logAssignNoOffset("heterogeneous-sg.c", 148, & second___9, "struct type_11 *", "second___9",
                    second___9, "struct type_11", "(struct type_11 *)tmp___20", 0);
  first___9->next = (void *)second___9;
  logAssignOffset("heterogeneous-sg.c", 148, first___9, "struct type_11", "*first___9",
                  & first___9->next, "void *", "first___9->next", first___9->next,
                  "void", "(void *)second___9", 0);
  tmp___21 = malloc(sizeof(struct type_12 ));
  logAssignNoOffset("heterogeneous-sg.c", 149, & tmp___21, "void *", "tmp___21", tmp___21,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_12 )", sizeof(struct type_12 ));
  first___10 = (struct type_12 *)tmp___21;
  logAssignNoOffset("heterogeneous-sg.c", 149, & first___10, "struct type_12 *", "first___10",
                    first___10, "struct type_12", "(struct type_12 *)tmp___21", 0);
  tmp___22 = malloc(sizeof(struct type_12 ));
  logAssignNoOffset("heterogeneous-sg.c", 149, & tmp___22, "void *", "tmp___22", tmp___22,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_12 )", sizeof(struct type_12 ));
  second___10 = (struct type_12 *)tmp___22;
  logAssignNoOffset("heterogeneous-sg.c", 149, & second___10, "struct type_12 *",
                    "second___10", second___10, "struct type_12", "(struct type_12 *)tmp___22",
                    0);
  first___10->next = (void *)second___10;
  logAssignOffset("heterogeneous-sg.c", 149, first___10, "struct type_12", "*first___10",
                  & first___10->next, "void *", "first___10->next", first___10->next,
                  "void", "(void *)second___10", 0);
  tmp___23 = malloc(sizeof(struct type_13 ));
  logAssignNoOffset("heterogeneous-sg.c", 150, & tmp___23, "void *", "tmp___23", tmp___23,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_13 )", sizeof(struct type_13 ));
  first___11 = (struct type_13 *)tmp___23;
  logAssignNoOffset("heterogeneous-sg.c", 150, & first___11, "struct type_13 *", "first___11",
                    first___11, "struct type_13", "(struct type_13 *)tmp___23", 0);
  tmp___24 = malloc(sizeof(struct type_13 ));
  logAssignNoOffset("heterogeneous-sg.c", 150, & tmp___24, "void *", "tmp___24", tmp___24,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_13 )", sizeof(struct type_13 ));
  second___11 = (struct type_13 *)tmp___24;
  logAssignNoOffset("heterogeneous-sg.c", 150, & second___11, "struct type_13 *",
                    "second___11", second___11, "struct type_13", "(struct type_13 *)tmp___24",
                    0);
  first___11->next = (void *)second___11;
  logAssignOffset("heterogeneous-sg.c", 150, first___11, "struct type_13", "*first___11",
                  & first___11->next, "void *", "first___11->next", first___11->next,
                  "void", "(void *)second___11", 0);
  tmp___25 = malloc(sizeof(struct type_14 ));
  logAssignNoOffset("heterogeneous-sg.c", 151, & tmp___25, "void *", "tmp___25", tmp___25,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_14 )", sizeof(struct type_14 ));
  first___12 = (struct type_14 *)tmp___25;
  logAssignNoOffset("heterogeneous-sg.c", 151, & first___12, "struct type_14 *", "first___12",
                    first___12, "struct type_14", "(struct type_14 *)tmp___25", 0);
  tmp___26 = malloc(sizeof(struct type_14 ));
  logAssignNoOffset("heterogeneous-sg.c", 151, & tmp___26, "void *", "tmp___26", tmp___26,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_14 )", sizeof(struct type_14 ));
  second___12 = (struct type_14 *)tmp___26;
  logAssignNoOffset("heterogeneous-sg.c", 151, & second___12, "struct type_14 *",
                    "second___12", second___12, "struct type_14", "(struct type_14 *)tmp___26",
                    0);
  first___12->next = (void *)second___12;
  logAssignOffset("heterogeneous-sg.c", 151, first___12, "struct type_14", "*first___12",
                  & first___12->next, "void *", "first___12->next", first___12->next,
                  "void", "(void *)second___12", 0);
  tmp___27 = malloc(sizeof(struct type_15 ));
  logAssignNoOffset("heterogeneous-sg.c", 152, & tmp___27, "void *", "tmp___27", tmp___27,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_15 )", sizeof(struct type_15 ));
  first___13 = (struct type_15 *)tmp___27;
  logAssignNoOffset("heterogeneous-sg.c", 152, & first___13, "struct type_15 *", "first___13",
                    first___13, "struct type_15", "(struct type_15 *)tmp___27", 0);
  tmp___28 = malloc(sizeof(struct type_15 ));
  logAssignNoOffset("heterogeneous-sg.c", 152, & tmp___28, "void *", "tmp___28", tmp___28,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_15 )", sizeof(struct type_15 ));
  second___13 = (struct type_15 *)tmp___28;
  logAssignNoOffset("heterogeneous-sg.c", 152, & second___13, "struct type_15 *",
                    "second___13", second___13, "struct type_15", "(struct type_15 *)tmp___28",
                    0);
  first___13->next = (void *)second___13;
  logAssignOffset("heterogeneous-sg.c", 152, first___13, "struct type_15", "*first___13",
                  & first___13->next, "void *", "first___13->next", first___13->next,
                  "void", "(void *)second___13", 0);
  tmp___29 = malloc(sizeof(struct type_16 ));
  logAssignNoOffset("heterogeneous-sg.c", 153, & tmp___29, "void *", "tmp___29", tmp___29,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_16 )", sizeof(struct type_16 ));
  first___14 = (struct type_16 *)tmp___29;
  logAssignNoOffset("heterogeneous-sg.c", 153, & first___14, "struct type_16 *", "first___14",
                    first___14, "struct type_16", "(struct type_16 *)tmp___29", 0);
  tmp___30 = malloc(sizeof(struct type_16 ));
  logAssignNoOffset("heterogeneous-sg.c", 153, & tmp___30, "void *", "tmp___30", tmp___30,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_16 )", sizeof(struct type_16 ));
  second___14 = (struct type_16 *)tmp___30;
  logAssignNoOffset("heterogeneous-sg.c", 153, & second___14, "struct type_16 *",
                    "second___14", second___14, "struct type_16", "(struct type_16 *)tmp___30",
                    0);
  first___14->next = (void *)second___14;
  logAssignOffset("heterogeneous-sg.c", 153, first___14, "struct type_16", "*first___14",
                  & first___14->next, "void *", "first___14->next", first___14->next,
                  "void", "(void *)second___14", 0);
  tmp___31 = malloc(sizeof(struct type_17 ));
  logAssignNoOffset("heterogeneous-sg.c", 154, & tmp___31, "void *", "tmp___31", tmp___31,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_17 )", sizeof(struct type_17 ));
  first___15 = (struct type_17 *)tmp___31;
  logAssignNoOffset("heterogeneous-sg.c", 154, & first___15, "struct type_17 *", "first___15",
                    first___15, "struct type_17", "(struct type_17 *)tmp___31", 0);
  tmp___32 = malloc(sizeof(struct type_17 ));
  logAssignNoOffset("heterogeneous-sg.c", 154, & tmp___32, "void *", "tmp___32", tmp___32,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_17 )", sizeof(struct type_17 ));
  second___15 = (struct type_17 *)tmp___32;
  logAssignNoOffset("heterogeneous-sg.c", 154, & second___15, "struct type_17 *",
                    "second___15", second___15, "struct type_17", "(struct type_17 *)tmp___32",
                    0);
  first___15->next = (void *)second___15;
  logAssignOffset("heterogeneous-sg.c", 154, first___15, "struct type_17", "*first___15",
                  & first___15->next, "void *", "first___15->next", first___15->next,
                  "void", "(void *)second___15", 0);
  tmp___33 = malloc(sizeof(struct type_18 ));
  logAssignNoOffset("heterogeneous-sg.c", 155, & tmp___33, "void *", "tmp___33", tmp___33,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_18 )", sizeof(struct type_18 ));
  first___16 = (struct type_18 *)tmp___33;
  logAssignNoOffset("heterogeneous-sg.c", 155, & first___16, "struct type_18 *", "first___16",
                    first___16, "struct type_18", "(struct type_18 *)tmp___33", 0);
  tmp___34 = malloc(sizeof(struct type_18 ));
  logAssignNoOffset("heterogeneous-sg.c", 155, & tmp___34, "void *", "tmp___34", tmp___34,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_18 )", sizeof(struct type_18 ));
  second___16 = (struct type_18 *)tmp___34;
  logAssignNoOffset("heterogeneous-sg.c", 155, & second___16, "struct type_18 *",
                    "second___16", second___16, "struct type_18", "(struct type_18 *)tmp___34",
                    0);
  first___16->next = (void *)second___16;
  logAssignOffset("heterogeneous-sg.c", 155, first___16, "struct type_18", "*first___16",
                  & first___16->next, "void *", "first___16->next", first___16->next,
                  "void", "(void *)second___16", 0);
  tmp___35 = malloc(sizeof(struct type_19 ));
  logAssignNoOffset("heterogeneous-sg.c", 156, & tmp___35, "void *", "tmp___35", tmp___35,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_19 )", sizeof(struct type_19 ));
  first___17 = (struct type_19 *)tmp___35;
  logAssignNoOffset("heterogeneous-sg.c", 156, & first___17, "struct type_19 *", "first___17",
                    first___17, "struct type_19", "(struct type_19 *)tmp___35", 0);
  tmp___36 = malloc(sizeof(struct type_19 ));
  logAssignNoOffset("heterogeneous-sg.c", 156, & tmp___36, "void *", "tmp___36", tmp___36,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_19 )", sizeof(struct type_19 ));
  second___17 = (struct type_19 *)tmp___36;
  logAssignNoOffset("heterogeneous-sg.c", 156, & second___17, "struct type_19 *",
                    "second___17", second___17, "struct type_19", "(struct type_19 *)tmp___36",
                    0);
  first___17->next = (void *)second___17;
  logAssignOffset("heterogeneous-sg.c", 156, first___17, "struct type_19", "*first___17",
                  & first___17->next, "void *", "first___17->next", first___17->next,
                  "void", "(void *)second___17", 0);
  tmp___37 = malloc(sizeof(struct type_20 ));
  logAssignNoOffset("heterogeneous-sg.c", 157, & tmp___37, "void *", "tmp___37", tmp___37,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_20 )", sizeof(struct type_20 ));
  first___18 = (struct type_20 *)tmp___37;
  logAssignNoOffset("heterogeneous-sg.c", 157, & first___18, "struct type_20 *", "first___18",
                    first___18, "struct type_20", "(struct type_20 *)tmp___37", 0);
  tmp___38 = malloc(sizeof(struct type_20 ));
  logAssignNoOffset("heterogeneous-sg.c", 157, & tmp___38, "void *", "tmp___38", tmp___38,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_20 )", sizeof(struct type_20 ));
  second___18 = (struct type_20 *)tmp___38;
  logAssignNoOffset("heterogeneous-sg.c", 157, & second___18, "struct type_20 *",
                    "second___18", second___18, "struct type_20", "(struct type_20 *)tmp___38",
                    0);
  first___18->next = (void *)second___18;
  logAssignOffset("heterogeneous-sg.c", 157, first___18, "struct type_20", "*first___18",
                  & first___18->next, "void *", "first___18->next", first___18->next,
                  "void", "(void *)second___18", 0);
  tmp___39 = malloc(sizeof(struct type_21 ));
  logAssignNoOffset("heterogeneous-sg.c", 158, & tmp___39, "void *", "tmp___39", tmp___39,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_21 )", sizeof(struct type_21 ));
  first___19 = (struct type_21 *)tmp___39;
  logAssignNoOffset("heterogeneous-sg.c", 158, & first___19, "struct type_21 *", "first___19",
                    first___19, "struct type_21", "(struct type_21 *)tmp___39", 0);
  tmp___40 = malloc(sizeof(struct type_21 ));
  logAssignNoOffset("heterogeneous-sg.c", 158, & tmp___40, "void *", "tmp___40", tmp___40,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_21 )", sizeof(struct type_21 ));
  second___19 = (struct type_21 *)tmp___40;
  logAssignNoOffset("heterogeneous-sg.c", 158, & second___19, "struct type_21 *",
                    "second___19", second___19, "struct type_21", "(struct type_21 *)tmp___40",
                    0);
  first___19->next = (void *)second___19;
  logAssignOffset("heterogeneous-sg.c", 158, first___19, "struct type_21", "*first___19",
                  & first___19->next, "void *", "first___19->next", first___19->next,
                  "void", "(void *)second___19", 0);
  tmp___41 = malloc(sizeof(struct type_22 ));
  logAssignNoOffset("heterogeneous-sg.c", 159, & tmp___41, "void *", "tmp___41", tmp___41,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_22 )", sizeof(struct type_22 ));
  first___20 = (struct type_22 *)tmp___41;
  logAssignNoOffset("heterogeneous-sg.c", 159, & first___20, "struct type_22 *", "first___20",
                    first___20, "struct type_22", "(struct type_22 *)tmp___41", 0);
  tmp___42 = malloc(sizeof(struct type_22 ));
  logAssignNoOffset("heterogeneous-sg.c", 159, & tmp___42, "void *", "tmp___42", tmp___42,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_22 )", sizeof(struct type_22 ));
  second___20 = (struct type_22 *)tmp___42;
  logAssignNoOffset("heterogeneous-sg.c", 159, & second___20, "struct type_22 *",
                    "second___20", second___20, "struct type_22", "(struct type_22 *)tmp___42",
                    0);
  first___20->next = (void *)second___20;
  logAssignOffset("heterogeneous-sg.c", 159, first___20, "struct type_22", "*first___20",
                  & first___20->next, "void *", "first___20->next", first___20->next,
                  "void", "(void *)second___20", 0);
  tmp___43 = malloc(sizeof(struct type_23 ));
  logAssignNoOffset("heterogeneous-sg.c", 160, & tmp___43, "void *", "tmp___43", tmp___43,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_23 )", sizeof(struct type_23 ));
  first___21 = (struct type_23 *)tmp___43;
  logAssignNoOffset("heterogeneous-sg.c", 160, & first___21, "struct type_23 *", "first___21",
                    first___21, "struct type_23", "(struct type_23 *)tmp___43", 0);
  tmp___44 = malloc(sizeof(struct type_23 ));
  logAssignNoOffset("heterogeneous-sg.c", 160, & tmp___44, "void *", "tmp___44", tmp___44,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_23 )", sizeof(struct type_23 ));
  second___21 = (struct type_23 *)tmp___44;
  logAssignNoOffset("heterogeneous-sg.c", 160, & second___21, "struct type_23 *",
                    "second___21", second___21, "struct type_23", "(struct type_23 *)tmp___44",
                    0);
  first___21->next = (void *)second___21;
  logAssignOffset("heterogeneous-sg.c", 160, first___21, "struct type_23", "*first___21",
                  & first___21->next, "void *", "first___21->next", first___21->next,
                  "void", "(void *)second___21", 0);
  tmp___45 = malloc(sizeof(struct type_24 ));
  logAssignNoOffset("heterogeneous-sg.c", 161, & tmp___45, "void *", "tmp___45", tmp___45,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_24 )", sizeof(struct type_24 ));
  first___22 = (struct type_24 *)tmp___45;
  logAssignNoOffset("heterogeneous-sg.c", 161, & first___22, "struct type_24 *", "first___22",
                    first___22, "struct type_24", "(struct type_24 *)tmp___45", 0);
  tmp___46 = malloc(sizeof(struct type_24 ));
  logAssignNoOffset("heterogeneous-sg.c", 161, & tmp___46, "void *", "tmp___46", tmp___46,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_24 )", sizeof(struct type_24 ));
  second___22 = (struct type_24 *)tmp___46;
  logAssignNoOffset("heterogeneous-sg.c", 161, & second___22, "struct type_24 *",
                    "second___22", second___22, "struct type_24", "(struct type_24 *)tmp___46",
                    0);
  first___22->next = (void *)second___22;
  logAssignOffset("heterogeneous-sg.c", 161, first___22, "struct type_24", "*first___22",
                  & first___22->next, "void *", "first___22->next", first___22->next,
                  "void", "(void *)second___22", 0);
  tmp___47 = malloc(sizeof(struct type_25 ));
  logAssignNoOffset("heterogeneous-sg.c", 162, & tmp___47, "void *", "tmp___47", tmp___47,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_25 )", sizeof(struct type_25 ));
  first___23 = (struct type_25 *)tmp___47;
  logAssignNoOffset("heterogeneous-sg.c", 162, & first___23, "struct type_25 *", "first___23",
                    first___23, "struct type_25", "(struct type_25 *)tmp___47", 0);
  tmp___48 = malloc(sizeof(struct type_25 ));
  logAssignNoOffset("heterogeneous-sg.c", 162, & tmp___48, "void *", "tmp___48", tmp___48,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_25 )", sizeof(struct type_25 ));
  second___23 = (struct type_25 *)tmp___48;
  logAssignNoOffset("heterogeneous-sg.c", 162, & second___23, "struct type_25 *",
                    "second___23", second___23, "struct type_25", "(struct type_25 *)tmp___48",
                    0);
  first___23->next = (void *)second___23;
  logAssignOffset("heterogeneous-sg.c", 162, first___23, "struct type_25", "*first___23",
                  & first___23->next, "void *", "first___23->next", first___23->next,
                  "void", "(void *)second___23", 0);
  tmp___49 = malloc(sizeof(struct type_26 ));
  logAssignNoOffset("heterogeneous-sg.c", 163, & tmp___49, "void *", "tmp___49", tmp___49,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_26 )", sizeof(struct type_26 ));
  first___24 = (struct type_26 *)tmp___49;
  logAssignNoOffset("heterogeneous-sg.c", 163, & first___24, "struct type_26 *", "first___24",
                    first___24, "struct type_26", "(struct type_26 *)tmp___49", 0);
  tmp___50 = malloc(sizeof(struct type_26 ));
  logAssignNoOffset("heterogeneous-sg.c", 163, & tmp___50, "void *", "tmp___50", tmp___50,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_26 )", sizeof(struct type_26 ));
  second___24 = (struct type_26 *)tmp___50;
  logAssignNoOffset("heterogeneous-sg.c", 163, & second___24, "struct type_26 *",
                    "second___24", second___24, "struct type_26", "(struct type_26 *)tmp___50",
                    0);
  first___24->next = (void *)second___24;
  logAssignOffset("heterogeneous-sg.c", 163, first___24, "struct type_26", "*first___24",
                  & first___24->next, "void *", "first___24->next", first___24->next,
                  "void", "(void *)second___24", 0);
  tmp___51 = malloc(sizeof(struct type_27 ));
  logAssignNoOffset("heterogeneous-sg.c", 164, & tmp___51, "void *", "tmp___51", tmp___51,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_27 )", sizeof(struct type_27 ));
  first___25 = (struct type_27 *)tmp___51;
  logAssignNoOffset("heterogeneous-sg.c", 164, & first___25, "struct type_27 *", "first___25",
                    first___25, "struct type_27", "(struct type_27 *)tmp___51", 0);
  tmp___52 = malloc(sizeof(struct type_27 ));
  logAssignNoOffset("heterogeneous-sg.c", 164, & tmp___52, "void *", "tmp___52", tmp___52,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_27 )", sizeof(struct type_27 ));
  second___25 = (struct type_27 *)tmp___52;
  logAssignNoOffset("heterogeneous-sg.c", 164, & second___25, "struct type_27 *",
                    "second___25", second___25, "struct type_27", "(struct type_27 *)tmp___52",
                    0);
  first___25->next = (void *)second___25;
  logAssignOffset("heterogeneous-sg.c", 164, first___25, "struct type_27", "*first___25",
                  & first___25->next, "void *", "first___25->next", first___25->next,
                  "void", "(void *)second___25", 0);
  tmp___53 = malloc(sizeof(struct type_28 ));
  logAssignNoOffset("heterogeneous-sg.c", 165, & tmp___53, "void *", "tmp___53", tmp___53,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_28 )", sizeof(struct type_28 ));
  first___26 = (struct type_28 *)tmp___53;
  logAssignNoOffset("heterogeneous-sg.c", 165, & first___26, "struct type_28 *", "first___26",
                    first___26, "struct type_28", "(struct type_28 *)tmp___53", 0);
  tmp___54 = malloc(sizeof(struct type_28 ));
  logAssignNoOffset("heterogeneous-sg.c", 165, & tmp___54, "void *", "tmp___54", tmp___54,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_28 )", sizeof(struct type_28 ));
  second___26 = (struct type_28 *)tmp___54;
  logAssignNoOffset("heterogeneous-sg.c", 165, & second___26, "struct type_28 *",
                    "second___26", second___26, "struct type_28", "(struct type_28 *)tmp___54",
                    0);
  first___26->next = (void *)second___26;
  logAssignOffset("heterogeneous-sg.c", 165, first___26, "struct type_28", "*first___26",
                  & first___26->next, "void *", "first___26->next", first___26->next,
                  "void", "(void *)second___26", 0);
  tmp___55 = malloc(sizeof(struct type_29 ));
  logAssignNoOffset("heterogeneous-sg.c", 166, & tmp___55, "void *", "tmp___55", tmp___55,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_29 )", sizeof(struct type_29 ));
  first___27 = (struct type_29 *)tmp___55;
  logAssignNoOffset("heterogeneous-sg.c", 166, & first___27, "struct type_29 *", "first___27",
                    first___27, "struct type_29", "(struct type_29 *)tmp___55", 0);
  tmp___56 = malloc(sizeof(struct type_29 ));
  logAssignNoOffset("heterogeneous-sg.c", 166, & tmp___56, "void *", "tmp___56", tmp___56,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_29 )", sizeof(struct type_29 ));
  second___27 = (struct type_29 *)tmp___56;
  logAssignNoOffset("heterogeneous-sg.c", 166, & second___27, "struct type_29 *",
                    "second___27", second___27, "struct type_29", "(struct type_29 *)tmp___56",
                    0);
  first___27->next = (void *)second___27;
  logAssignOffset("heterogeneous-sg.c", 166, first___27, "struct type_29", "*first___27",
                  & first___27->next, "void *", "first___27->next", first___27->next,
                  "void", "(void *)second___27", 0);
  tmp___57 = malloc(sizeof(struct type_30 ));
  logAssignNoOffset("heterogeneous-sg.c", 167, & tmp___57, "void *", "tmp___57", tmp___57,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_30 )", sizeof(struct type_30 ));
  first___28 = (struct type_30 *)tmp___57;
  logAssignNoOffset("heterogeneous-sg.c", 167, & first___28, "struct type_30 *", "first___28",
                    first___28, "struct type_30", "(struct type_30 *)tmp___57", 0);
  tmp___58 = malloc(sizeof(struct type_30 ));
  logAssignNoOffset("heterogeneous-sg.c", 167, & tmp___58, "void *", "tmp___58", tmp___58,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_30 )", sizeof(struct type_30 ));
  second___28 = (struct type_30 *)tmp___58;
  logAssignNoOffset("heterogeneous-sg.c", 167, & second___28, "struct type_30 *",
                    "second___28", second___28, "struct type_30", "(struct type_30 *)tmp___58",
                    0);
  first___28->next = (void *)second___28;
  logAssignOffset("heterogeneous-sg.c", 167, first___28, "struct type_30", "*first___28",
                  & first___28->next, "void *", "first___28->next", first___28->next,
                  "void", "(void *)second___28", 0);
  tmp___59 = malloc(sizeof(struct type_31 ));
  logAssignNoOffset("heterogeneous-sg.c", 168, & tmp___59, "void *", "tmp___59", tmp___59,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_31 )", sizeof(struct type_31 ));
  first___29 = (struct type_31 *)tmp___59;
  logAssignNoOffset("heterogeneous-sg.c", 168, & first___29, "struct type_31 *", "first___29",
                    first___29, "struct type_31", "(struct type_31 *)tmp___59", 0);
  tmp___60 = malloc(sizeof(struct type_31 ));
  logAssignNoOffset("heterogeneous-sg.c", 168, & tmp___60, "void *", "tmp___60", tmp___60,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_31 )", sizeof(struct type_31 ));
  second___29 = (struct type_31 *)tmp___60;
  logAssignNoOffset("heterogeneous-sg.c", 168, & second___29, "struct type_31 *",
                    "second___29", second___29, "struct type_31", "(struct type_31 *)tmp___60",
                    0);
  first___29->next = (void *)second___29;
  logAssignOffset("heterogeneous-sg.c", 168, first___29, "struct type_31", "*first___29",
                  & first___29->next, "void *", "first___29->next", first___29->next,
                  "void", "(void *)second___29", 0);
  tmp___61 = malloc(sizeof(struct type_32 ));
  logAssignNoOffset("heterogeneous-sg.c", 169, & tmp___61, "void *", "tmp___61", tmp___61,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_32 )", sizeof(struct type_32 ));
  first___30 = (struct type_32 *)tmp___61;
  logAssignNoOffset("heterogeneous-sg.c", 169, & first___30, "struct type_32 *", "first___30",
                    first___30, "struct type_32", "(struct type_32 *)tmp___61", 0);
  tmp___62 = malloc(sizeof(struct type_32 ));
  logAssignNoOffset("heterogeneous-sg.c", 169, & tmp___62, "void *", "tmp___62", tmp___62,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_32 )", sizeof(struct type_32 ));
  second___30 = (struct type_32 *)tmp___62;
  logAssignNoOffset("heterogeneous-sg.c", 169, & second___30, "struct type_32 *",
                    "second___30", second___30, "struct type_32", "(struct type_32 *)tmp___62",
                    0);
  first___30->next = (void *)second___30;
  logAssignOffset("heterogeneous-sg.c", 169, first___30, "struct type_32", "*first___30",
                  & first___30->next, "void *", "first___30->next", first___30->next,
                  "void", "(void *)second___30", 0);
  tmp___63 = malloc(sizeof(struct type_33 ));
  logAssignNoOffset("heterogeneous-sg.c", 170, & tmp___63, "void *", "tmp___63", tmp___63,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_33 )", sizeof(struct type_33 ));
  first___31 = (struct type_33 *)tmp___63;
  logAssignNoOffset("heterogeneous-sg.c", 170, & first___31, "struct type_33 *", "first___31",
                    first___31, "struct type_33", "(struct type_33 *)tmp___63", 0);
  tmp___64 = malloc(sizeof(struct type_33 ));
  logAssignNoOffset("heterogeneous-sg.c", 170, & tmp___64, "void *", "tmp___64", tmp___64,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_33 )", sizeof(struct type_33 ));
  second___31 = (struct type_33 *)tmp___64;
  logAssignNoOffset("heterogeneous-sg.c", 170, & second___31, "struct type_33 *",
                    "second___31", second___31, "struct type_33", "(struct type_33 *)tmp___64",
                    0);
  first___31->next = (void *)second___31;
  logAssignOffset("heterogeneous-sg.c", 170, first___31, "struct type_33", "*first___31",
                  & first___31->next, "void *", "first___31->next", first___31->next,
                  "void", "(void *)second___31", 0);
  tmp___65 = malloc(sizeof(struct type_34 ));
  logAssignNoOffset("heterogeneous-sg.c", 171, & tmp___65, "void *", "tmp___65", tmp___65,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_34 )", sizeof(struct type_34 ));
  first___32 = (struct type_34 *)tmp___65;
  logAssignNoOffset("heterogeneous-sg.c", 171, & first___32, "struct type_34 *", "first___32",
                    first___32, "struct type_34", "(struct type_34 *)tmp___65", 0);
  tmp___66 = malloc(sizeof(struct type_34 ));
  logAssignNoOffset("heterogeneous-sg.c", 171, & tmp___66, "void *", "tmp___66", tmp___66,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_34 )", sizeof(struct type_34 ));
  second___32 = (struct type_34 *)tmp___66;
  logAssignNoOffset("heterogeneous-sg.c", 171, & second___32, "struct type_34 *",
                    "second___32", second___32, "struct type_34", "(struct type_34 *)tmp___66",
                    0);
  first___32->next = (void *)second___32;
  logAssignOffset("heterogeneous-sg.c", 171, first___32, "struct type_34", "*first___32",
                  & first___32->next, "void *", "first___32->next", first___32->next,
                  "void", "(void *)second___32", 0);
  tmp___67 = malloc(sizeof(struct type_35 ));
  logAssignNoOffset("heterogeneous-sg.c", 172, & tmp___67, "void *", "tmp___67", tmp___67,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_35 )", sizeof(struct type_35 ));
  first___33 = (struct type_35 *)tmp___67;
  logAssignNoOffset("heterogeneous-sg.c", 172, & first___33, "struct type_35 *", "first___33",
                    first___33, "struct type_35", "(struct type_35 *)tmp___67", 0);
  tmp___68 = malloc(sizeof(struct type_35 ));
  logAssignNoOffset("heterogeneous-sg.c", 172, & tmp___68, "void *", "tmp___68", tmp___68,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_35 )", sizeof(struct type_35 ));
  second___33 = (struct type_35 *)tmp___68;
  logAssignNoOffset("heterogeneous-sg.c", 172, & second___33, "struct type_35 *",
                    "second___33", second___33, "struct type_35", "(struct type_35 *)tmp___68",
                    0);
  first___33->next = (void *)second___33;
  logAssignOffset("heterogeneous-sg.c", 172, first___33, "struct type_35", "*first___33",
                  & first___33->next, "void *", "first___33->next", first___33->next,
                  "void", "(void *)second___33", 0);
  tmp___69 = malloc(sizeof(struct type_36 ));
  logAssignNoOffset("heterogeneous-sg.c", 173, & tmp___69, "void *", "tmp___69", tmp___69,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_36 )", sizeof(struct type_36 ));
  first___34 = (struct type_36 *)tmp___69;
  logAssignNoOffset("heterogeneous-sg.c", 173, & first___34, "struct type_36 *", "first___34",
                    first___34, "struct type_36", "(struct type_36 *)tmp___69", 0);
  tmp___70 = malloc(sizeof(struct type_36 ));
  logAssignNoOffset("heterogeneous-sg.c", 173, & tmp___70, "void *", "tmp___70", tmp___70,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_36 )", sizeof(struct type_36 ));
  second___34 = (struct type_36 *)tmp___70;
  logAssignNoOffset("heterogeneous-sg.c", 173, & second___34, "struct type_36 *",
                    "second___34", second___34, "struct type_36", "(struct type_36 *)tmp___70",
                    0);
  first___34->next = (void *)second___34;
  logAssignOffset("heterogeneous-sg.c", 173, first___34, "struct type_36", "*first___34",
                  & first___34->next, "void *", "first___34->next", first___34->next,
                  "void", "(void *)second___34", 0);
  tmp___71 = malloc(sizeof(struct type_37 ));
  logAssignNoOffset("heterogeneous-sg.c", 174, & tmp___71, "void *", "tmp___71", tmp___71,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_37 )", sizeof(struct type_37 ));
  first___35 = (struct type_37 *)tmp___71;
  logAssignNoOffset("heterogeneous-sg.c", 174, & first___35, "struct type_37 *", "first___35",
                    first___35, "struct type_37", "(struct type_37 *)tmp___71", 0);
  tmp___72 = malloc(sizeof(struct type_37 ));
  logAssignNoOffset("heterogeneous-sg.c", 174, & tmp___72, "void *", "tmp___72", tmp___72,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_37 )", sizeof(struct type_37 ));
  second___35 = (struct type_37 *)tmp___72;
  logAssignNoOffset("heterogeneous-sg.c", 174, & second___35, "struct type_37 *",
                    "second___35", second___35, "struct type_37", "(struct type_37 *)tmp___72",
                    0);
  first___35->next = (void *)second___35;
  logAssignOffset("heterogeneous-sg.c", 174, first___35, "struct type_37", "*first___35",
                  & first___35->next, "void *", "first___35->next", first___35->next,
                  "void", "(void *)second___35", 0);
  tmp___73 = malloc(sizeof(struct type_38 ));
  logAssignNoOffset("heterogeneous-sg.c", 175, & tmp___73, "void *", "tmp___73", tmp___73,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_38 )", sizeof(struct type_38 ));
  first___36 = (struct type_38 *)tmp___73;
  logAssignNoOffset("heterogeneous-sg.c", 175, & first___36, "struct type_38 *", "first___36",
                    first___36, "struct type_38", "(struct type_38 *)tmp___73", 0);
  tmp___74 = malloc(sizeof(struct type_38 ));
  logAssignNoOffset("heterogeneous-sg.c", 175, & tmp___74, "void *", "tmp___74", tmp___74,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_38 )", sizeof(struct type_38 ));
  second___36 = (struct type_38 *)tmp___74;
  logAssignNoOffset("heterogeneous-sg.c", 175, & second___36, "struct type_38 *",
                    "second___36", second___36, "struct type_38", "(struct type_38 *)tmp___74",
                    0);
  first___36->next = (void *)second___36;
  logAssignOffset("heterogeneous-sg.c", 175, first___36, "struct type_38", "*first___36",
                  & first___36->next, "void *", "first___36->next", first___36->next,
                  "void", "(void *)second___36", 0);
  tmp___75 = malloc(sizeof(struct type_39 ));
  logAssignNoOffset("heterogeneous-sg.c", 176, & tmp___75, "void *", "tmp___75", tmp___75,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_39 )", sizeof(struct type_39 ));
  first___37 = (struct type_39 *)tmp___75;
  logAssignNoOffset("heterogeneous-sg.c", 176, & first___37, "struct type_39 *", "first___37",
                    first___37, "struct type_39", "(struct type_39 *)tmp___75", 0);
  tmp___76 = malloc(sizeof(struct type_39 ));
  logAssignNoOffset("heterogeneous-sg.c", 176, & tmp___76, "void *", "tmp___76", tmp___76,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_39 )", sizeof(struct type_39 ));
  second___37 = (struct type_39 *)tmp___76;
  logAssignNoOffset("heterogeneous-sg.c", 176, & second___37, "struct type_39 *",
                    "second___37", second___37, "struct type_39", "(struct type_39 *)tmp___76",
                    0);
  first___37->next = (void *)second___37;
  logAssignOffset("heterogeneous-sg.c", 176, first___37, "struct type_39", "*first___37",
                  & first___37->next, "void *", "first___37->next", first___37->next,
                  "void", "(void *)second___37", 0);
  tmp___77 = malloc(sizeof(struct type_40 ));
  logAssignNoOffset("heterogeneous-sg.c", 177, & tmp___77, "void *", "tmp___77", tmp___77,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_40 )", sizeof(struct type_40 ));
  first___38 = (struct type_40 *)tmp___77;
  logAssignNoOffset("heterogeneous-sg.c", 177, & first___38, "struct type_40 *", "first___38",
                    first___38, "struct type_40", "(struct type_40 *)tmp___77", 0);
  tmp___78 = malloc(sizeof(struct type_40 ));
  logAssignNoOffset("heterogeneous-sg.c", 177, & tmp___78, "void *", "tmp___78", tmp___78,
                    "void", "malloc", 1);
  logMallocInfo("sizeof(struct type_40 )", sizeof(struct type_40 ));
  second___38 = (struct type_40 *)tmp___78;
  logAssignNoOffset("heterogeneous-sg.c", 177, & second___38, "struct type_40 *",
                    "second___38", second___38, "struct type_40", "(struct type_40 *)tmp___78",
                    0);
  first___38->next = (void *)second___38;
  logAssignOffset("heterogeneous-sg.c", 177, first___38, "struct type_40", "*first___38",
                  & first___38->next, "void *", "first___38->next", first___38->next,
                  "void", "(void *)second___38", 0);
  logBlockExit("heterogeneous-sg.c", 177);
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("head", & head);
  logVarOutOfScope("last_elem", & last_elem);
  logVarOutOfScope("first", & first);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("second", & second);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("first___0", & first___0);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("second___0", & second___0);
  logVarOutOfScope("tmp___2", & tmp___2);
  logVarOutOfScope("first___1", & first___1);
  logVarOutOfScope("tmp___3", & tmp___3);
  logVarOutOfScope("second___1", & second___1);
  logVarOutOfScope("tmp___4", & tmp___4);
  logVarOutOfScope("first___2", & first___2);
  logVarOutOfScope("tmp___5", & tmp___5);
  logVarOutOfScope("second___2", & second___2);
  logVarOutOfScope("tmp___6", & tmp___6);
  logVarOutOfScope("first___3", & first___3);
  logVarOutOfScope("tmp___7", & tmp___7);
  logVarOutOfScope("second___3", & second___3);
  logVarOutOfScope("tmp___8", & tmp___8);
  logVarOutOfScope("first___4", & first___4);
  logVarOutOfScope("tmp___9", & tmp___9);
  logVarOutOfScope("second___4", & second___4);
  logVarOutOfScope("tmp___10", & tmp___10);
  logVarOutOfScope("first___5", & first___5);
  logVarOutOfScope("tmp___11", & tmp___11);
  logVarOutOfScope("second___5", & second___5);
  logVarOutOfScope("tmp___12", & tmp___12);
  logVarOutOfScope("first___6", & first___6);
  logVarOutOfScope("tmp___13", & tmp___13);
  logVarOutOfScope("second___6", & second___6);
  logVarOutOfScope("tmp___14", & tmp___14);
  logVarOutOfScope("first___7", & first___7);
  logVarOutOfScope("tmp___15", & tmp___15);
  logVarOutOfScope("second___7", & second___7);
  logVarOutOfScope("tmp___16", & tmp___16);
  logVarOutOfScope("first___8", & first___8);
  logVarOutOfScope("tmp___17", & tmp___17);
  logVarOutOfScope("second___8", & second___8);
  logVarOutOfScope("tmp___18", & tmp___18);
  logVarOutOfScope("first___9", & first___9);
  logVarOutOfScope("tmp___19", & tmp___19);
  logVarOutOfScope("second___9", & second___9);
  logVarOutOfScope("tmp___20", & tmp___20);
  logVarOutOfScope("first___10", & first___10);
  logVarOutOfScope("tmp___21", & tmp___21);
  logVarOutOfScope("second___10", & second___10);
  logVarOutOfScope("tmp___22", & tmp___22);
  logVarOutOfScope("first___11", & first___11);
  logVarOutOfScope("tmp___23", & tmp___23);
  logVarOutOfScope("second___11", & second___11);
  logVarOutOfScope("tmp___24", & tmp___24);
  logVarOutOfScope("first___12", & first___12);
  logVarOutOfScope("tmp___25", & tmp___25);
  logVarOutOfScope("second___12", & second___12);
  logVarOutOfScope("tmp___26", & tmp___26);
  logVarOutOfScope("first___13", & first___13);
  logVarOutOfScope("tmp___27", & tmp___27);
  logVarOutOfScope("second___13", & second___13);
  logVarOutOfScope("tmp___28", & tmp___28);
  logVarOutOfScope("first___14", & first___14);
  logVarOutOfScope("tmp___29", & tmp___29);
  logVarOutOfScope("second___14", & second___14);
  logVarOutOfScope("tmp___30", & tmp___30);
  logVarOutOfScope("first___15", & first___15);
  logVarOutOfScope("tmp___31", & tmp___31);
  logVarOutOfScope("second___15", & second___15);
  logVarOutOfScope("tmp___32", & tmp___32);
  logVarOutOfScope("first___16", & first___16);
  logVarOutOfScope("tmp___33", & tmp___33);
  logVarOutOfScope("second___16", & second___16);
  logVarOutOfScope("tmp___34", & tmp___34);
  logVarOutOfScope("first___17", & first___17);
  logVarOutOfScope("tmp___35", & tmp___35);
  logVarOutOfScope("second___17", & second___17);
  logVarOutOfScope("tmp___36", & tmp___36);
  logVarOutOfScope("first___18", & first___18);
  logVarOutOfScope("tmp___37", & tmp___37);
  logVarOutOfScope("second___18", & second___18);
  logVarOutOfScope("tmp___38", & tmp___38);
  logVarOutOfScope("first___19", & first___19);
  logVarOutOfScope("tmp___39", & tmp___39);
  logVarOutOfScope("second___19", & second___19);
  logVarOutOfScope("tmp___40", & tmp___40);
  logVarOutOfScope("first___20", & first___20);
  logVarOutOfScope("tmp___41", & tmp___41);
  logVarOutOfScope("second___20", & second___20);
  logVarOutOfScope("tmp___42", & tmp___42);
  logVarOutOfScope("first___21", & first___21);
  logVarOutOfScope("tmp___43", & tmp___43);
  logVarOutOfScope("second___21", & second___21);
  logVarOutOfScope("tmp___44", & tmp___44);
  logVarOutOfScope("first___22", & first___22);
  logVarOutOfScope("tmp___45", & tmp___45);
  logVarOutOfScope("second___22", & second___22);
  logVarOutOfScope("tmp___46", & tmp___46);
  logVarOutOfScope("first___23", & first___23);
  logVarOutOfScope("tmp___47", & tmp___47);
  logVarOutOfScope("second___23", & second___23);
  logVarOutOfScope("tmp___48", & tmp___48);
  logVarOutOfScope("first___24", & first___24);
  logVarOutOfScope("tmp___49", & tmp___49);
  logVarOutOfScope("second___24", & second___24);
  logVarOutOfScope("tmp___50", & tmp___50);
  logVarOutOfScope("first___25", & first___25);
  logVarOutOfScope("tmp___51", & tmp___51);
  logVarOutOfScope("second___25", & second___25);
  logVarOutOfScope("tmp___52", & tmp___52);
  logVarOutOfScope("first___26", & first___26);
  logVarOutOfScope("tmp___53", & tmp___53);
  logVarOutOfScope("second___26", & second___26);
  logVarOutOfScope("tmp___54", & tmp___54);
  logVarOutOfScope("first___27", & first___27);
  logVarOutOfScope("tmp___55", & tmp___55);
  logVarOutOfScope("second___27", & second___27);
  logVarOutOfScope("tmp___56", & tmp___56);
  logVarOutOfScope("first___28", & first___28);
  logVarOutOfScope("tmp___57", & tmp___57);
  logVarOutOfScope("second___28", & second___28);
  logVarOutOfScope("tmp___58", & tmp___58);
  logVarOutOfScope("first___29", & first___29);
  logVarOutOfScope("tmp___59", & tmp___59);
  logVarOutOfScope("second___29", & second___29);
  logVarOutOfScope("tmp___60", & tmp___60);
  logVarOutOfScope("first___30", & first___30);
  logVarOutOfScope("tmp___61", & tmp___61);
  logVarOutOfScope("second___30", & second___30);
  logVarOutOfScope("tmp___62", & tmp___62);
  logVarOutOfScope("first___31", & first___31);
  logVarOutOfScope("tmp___63", & tmp___63);
  logVarOutOfScope("second___31", & second___31);
  logVarOutOfScope("tmp___64", & tmp___64);
  logVarOutOfScope("first___32", & first___32);
  logVarOutOfScope("tmp___65", & tmp___65);
  logVarOutOfScope("second___32", & second___32);
  logVarOutOfScope("tmp___66", & tmp___66);
  logVarOutOfScope("first___33", & first___33);
  logVarOutOfScope("tmp___67", & tmp___67);
  logVarOutOfScope("second___33", & second___33);
  logVarOutOfScope("tmp___68", & tmp___68);
  logVarOutOfScope("first___34", & first___34);
  logVarOutOfScope("tmp___69", & tmp___69);
  logVarOutOfScope("second___34", & second___34);
  logVarOutOfScope("tmp___70", & tmp___70);
  logVarOutOfScope("first___35", & first___35);
  logVarOutOfScope("tmp___71", & tmp___71);
  logVarOutOfScope("second___35", & second___35);
  logVarOutOfScope("tmp___72", & tmp___72);
  logVarOutOfScope("first___36", & first___36);
  logVarOutOfScope("tmp___73", & tmp___73);
  logVarOutOfScope("second___36", & second___36);
  logVarOutOfScope("tmp___74", & tmp___74);
  logVarOutOfScope("first___37", & first___37);
  logVarOutOfScope("tmp___75", & tmp___75);
  logVarOutOfScope("second___37", & second___37);
  logVarOutOfScope("tmp___76", & tmp___76);
  logVarOutOfScope("first___38", & first___38);
  logVarOutOfScope("tmp___77", & tmp___77);
  logVarOutOfScope("second___38", & second___38);
  logVarOutOfScope("tmp___78", & tmp___78);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
