/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   struct node *next ;
   int value ;
};
struct list {
   struct node *head ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
struct list *list_create(void) ;
struct node *node_malloc(int item ) ;
void list_add(struct list *l , struct node *new ) ;
int list_remove(struct list *l ) ;
void list_dispose(struct list *l ) ;
void list_add(struct list *l , struct node *new ) 
{ 
  struct node *n ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct list *", & l);
  logVarInScope("formal", "new", "struct node *", & new);
  logVarInScope("local", "n", "struct node *", & n);
  logBlockEntry("sll_4.c", 20);
  n = l->head;
  logAssignNoOffset("sll_4.c", 20, & n, "struct node *", "n", n, "struct node", "l->head",
                    0);
  logBlockExit("sll_4.c", 20);
  if ((unsigned long )n == (unsigned long )((struct node *)0)) {
    logBlockEntry("sll_4.c", 22);
    l->head = new;
    logAssignOffset("sll_4.c", 22, l, "struct list", "*l", & l->head, "struct node *",
                    "l->head", l->head, "struct node", "new", 0);
    logBlockExit("sll_4.c", 22);
  } else {
    while ((unsigned long )n->next != (unsigned long )((struct node *)0)) {
      logComment("Loop-iteration-start_sll_4.c_24");
      {
      logBlockEntry("sll_4.c", 26);
      n = n->next;
      logAssignNoOffset("sll_4.c", 26, & n, "struct node *", "n", n, "struct node",
                        "n->next", 0);
      logBlockExit("sll_4.c", 26);
      }
      logComment("Loop-iteration-end");
    }
    logBlockEntry("sll_4.c", 28);
    n->next = new;
    logAssignOffset("sll_4.c", 28, n, "struct node", "*n", & n->next, "struct node *",
                    "n->next", n->next, "struct node", "new", 0);
    logBlockExit("sll_4.c", 28);
  }
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("new", & new);
  logVarOutOfScope("n", & n);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
struct list *list_create(void) 
{ 
  struct list *l ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "struct list *", & l);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("sll_4.c", 34);
  tmp = malloc(sizeof(struct list ));
  logAssignNoOffset("sll_4.c", 34, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct list )", sizeof(struct list ));
  l = (struct list *)tmp;
  logAssignNoOffset("sll_4.c", 34, & l, "struct list *", "l", l, "struct list", "(struct list *)tmp",
                    0);
  logBlockExit("sll_4.c", 34);
  if ((unsigned long )l == (unsigned long )((struct list *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_4.c", 36);
  l->head = (struct node *)0;
  logAssignOffset("sll_4.c", 36, l, "struct list", "*l", & l->head, "struct node *",
                  "l->head", l->head, "struct node", "(struct node *)0", 0);
  logBlockExit("sll_4.c", 36);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (l);
  }
  }
}
}
void list_dispose(struct list *l ) 
{ 
  struct node *current ;
  struct node *oldcurrent ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct list *", & l);
  logVarInScope("local", "current", "struct node *", & current);
  logVarInScope("local", "oldcurrent", "struct node *", & oldcurrent);
  logBlockEntry("sll_4.c", 42);
  current = l->head;
  logAssignNoOffset("sll_4.c", 42, & current, "struct node *", "current", current,
                    "struct node", "l->head", 0);
  logBlockExit("sll_4.c", 42);
  while ((unsigned long )current != (unsigned long )((struct node *)0)) {
    logComment("Loop-iteration-start_sll_4.c_43");
    {
    logBlockEntry("sll_4.c", 45);
    oldcurrent = current;
    logAssignNoOffset("sll_4.c", 45, & oldcurrent, "struct node *", "oldcurrent",
                      oldcurrent, "struct node", "current", 0);
    current = current->next;
    logAssignNoOffset("sll_4.c", 46, & current, "struct node *", "current", current,
                      "struct node", "current->next", 0);
    logFree("sll_4.c", 47, "(void *)oldcurrent", (void *)oldcurrent);
    free((void *)oldcurrent);
    logBlockExit("sll_4.c", 47);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("", -1);
  logFree("sll_4.c", 49, "(void *)l", (void *)l);
  free((void *)l);
  logBlockExit("sll_4.c", 49);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("current", & current);
  logVarOutOfScope("oldcurrent", & oldcurrent);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int list_remove(struct list *l ) 
{ 
  struct node *n ;
  int i ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "struct list *", & l);
  logVarInScope("local", "n", "struct node *", & n);
  logBlockEntry("sll_4.c", 55);
  n = l->head;
  logAssignNoOffset("sll_4.c", 55, & n, "struct node *", "n", n, "struct node", "l->head",
                    0);
  i = n->value;
  l->head = n->next;
  logAssignOffset("sll_4.c", 57, l, "struct list", "*l", & l->head, "struct node *",
                  "l->head", l->head, "struct node", "n->next", 0);
  logFree("sll_4.c", 58, "(void *)n", (void *)n);
  free((void *)n);
  logBlockExit("sll_4.c", 58);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("n", & n);
  {
  logComment("Function Exited");
  return (i);
  }
  }
}
}
struct node *node_malloc(int item ) 
{ 
  struct node *new ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "new", "struct node *", & new);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("sll_4.c", 64);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("sll_4.c", 64, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  new = (struct node *)tmp;
  logAssignNoOffset("sll_4.c", 64, & new, "struct node *", "new", new, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("sll_4.c", 64);
  if ((unsigned long )new == (unsigned long )((struct node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_4.c", 66);
  new->next = (struct node *)0;
  logAssignOffset("sll_4.c", 66, new, "struct node", "*new", & new->next, "struct node *",
                  "new->next", new->next, "struct node", "(struct node *)0", 0);
  new->value = item;
  logBlockExit("sll_4.c", 67);
  {
  logVarOutOfScope("new", & new);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (new);
  }
  }
}
}
int main(void) 
{ 
  int i ;
  struct list *l ;
  struct list *tmp ;
  struct node *n1 ;
  struct node *tmp___0 ;
  struct node *n2 ;
  struct node *tmp___1 ;
  struct node *n3 ;
  struct node *tmp___2 ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "struct list *", & l);
  logVarInScope("local", "tmp", "struct list *", & tmp);
  logVarInScope("local", "n1", "struct node *", & n1);
  logVarInScope("local", "tmp___0", "struct node *", & tmp___0);
  logVarInScope("local", "n2", "struct node *", & n2);
  logVarInScope("local", "tmp___1", "struct node *", & tmp___1);
  logVarInScope("local", "n3", "struct node *", & n3);
  logVarInScope("local", "tmp___2", "struct node *", & tmp___2);
  tmp = list_create();
  logBlockEntry("sll_4.c", 76);
  logAssignNoOffset("sll_4.c", 76, & tmp, "struct list *", "tmp", tmp, "struct list",
                    "list_create", 0);
  dumpVarsOutOfScope();
  l = tmp;
  logAssignNoOffset("sll_4.c", 76, & l, "struct list *", "l", l, "struct list", "tmp",
                    0);
  logBlockExit("sll_4.c", 77);
  tmp___0 = node_malloc(1);
  logBlockEntry("sll_4.c", 77);
  logAssignNoOffset("sll_4.c", 77, & tmp___0, "struct node *", "tmp___0", tmp___0,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n1 = tmp___0;
  logAssignNoOffset("sll_4.c", 77, & n1, "struct node *", "n1", n1, "struct node",
                    "tmp___0", 0);
  logBlockExit("sll_4.c", 78);
  tmp___1 = node_malloc(2);
  logBlockEntry("sll_4.c", 78);
  logAssignNoOffset("sll_4.c", 78, & tmp___1, "struct node *", "tmp___1", tmp___1,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n2 = tmp___1;
  logAssignNoOffset("sll_4.c", 78, & n2, "struct node *", "n2", n2, "struct node",
                    "tmp___1", 0);
  logBlockExit("sll_4.c", 79);
  tmp___2 = node_malloc(3);
  logBlockEntry("sll_4.c", 79);
  logAssignNoOffset("sll_4.c", 79, & tmp___2, "struct node *", "tmp___2", tmp___2,
                    "struct node", "node_malloc", 0);
  dumpVarsOutOfScope();
  n3 = tmp___2;
  logAssignNoOffset("sll_4.c", 79, & n3, "struct node *", "n3", n3, "struct node",
                    "tmp___2", 0);
  logBlockExit("sll_4.c", 80);
  list_add(l, n1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_4.c", 81);
  list_add(l, n2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_4.c", 82);
  list_add(l, n3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_4.c", 83);
  i = list_remove(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_4.c", 84);
  list_dispose(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("n1", & n1);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("n2", & n2);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("n3", & n3);
  logVarOutOfScope("tmp___2", & tmp___2);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
