/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   int item ;
   struct node *next ;
   struct node *prev ;
};
struct dll {
   struct node *head ;
   struct node *tail ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
void insertHead(struct dll *dll , int item ) ;
struct dll *create(void) ;
struct node *node_malloc(int item ) ;
void insertHead(struct dll *dll , int item ) 
{ 
  struct node *node ;
  struct node *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "dll", "struct dll *", & dll);
  logVarInScope("local", "node", "struct node *", & node);
  logVarInScope("local", "tmp", "struct node *", & tmp);
  tmp = node_malloc(item);
  logBlockEntry("dll_3.c", 23);
  logAssignNoOffset("dll_3.c", 23, & tmp, "struct node *", "tmp", tmp, "struct node",
                    "node_malloc", 0);
  dumpVarsOutOfScope();
  node = tmp;
  logAssignNoOffset("dll_3.c", 23, & node, "struct node *", "node", node, "struct node",
                    "tmp", 0);
  logBlockExit("dll_3.c", 23);
  if ((unsigned long )dll->head == (unsigned long )((void *)0)) {
    if ((unsigned long )dll->tail == (unsigned long )((void *)0)) {
      logBlockEntry("dll_3.c", 25);
      dll->head = node;
      logAssignOffset("dll_3.c", 25, dll, "struct dll", "*dll", & dll->head, "struct node *",
                      "dll->head", dll->head, "struct node", "node", 0);
      dll->tail = node;
      logAssignOffset("dll_3.c", 26, dll, "struct dll", "*dll", & dll->tail, "struct node *",
                      "dll->tail", dll->tail, "struct node", "node", 0);
      logBlockExit("dll_3.c", 26);
    } else {
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
  if ((unsigned long )dll->head != (unsigned long )((void *)0)) {
    if ((unsigned long )dll->tail != (unsigned long )((void *)0)) {
      logBlockEntry("dll_3.c", 28);
      node->next = dll->head;
      logAssignOffset("dll_3.c", 28, node, "struct node", "*node", & node->next, "struct node *",
                      "node->next", node->next, "struct node", "dll->head", 0);
      (dll->head)->prev = node;
      logAssignOffset("dll_3.c", 29, dll->head, "struct node", "*(dll->head)", & (dll->head)->prev,
                      "struct node *", "(dll->head)->prev", (dll->head)->prev, "struct node",
                      "node", 0);
      dll->head = node;
      logAssignOffset("dll_3.c", 30, dll, "struct dll", "*dll", & dll->head, "struct node *",
                      "dll->head", dll->head, "struct node", "node", 0);
      logBlockExit("dll_3.c", 30);
    } else {
      abort();
      logBlockEntry("", -1);
      dumpVarsOutOfScope();
      logBlockExit("", -1);
    }
  } else {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
struct dll *create(void) 
{ 
  struct dll *dll ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "dll", "struct dll *", & dll);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_3.c", 38);
  tmp = malloc(sizeof(struct dll ));
  logAssignNoOffset("dll_3.c", 38, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct dll )", sizeof(struct dll ));
  dll = (struct dll *)tmp;
  logAssignNoOffset("dll_3.c", 38, & dll, "struct dll *", "dll", dll, "struct dll",
                    "(struct dll *)tmp", 0);
  logBlockExit("dll_3.c", 38);
  if ((unsigned long )dll == (unsigned long )((void *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_3.c", 40);
  dll->head = (struct node *)((void *)0);
  logAssignOffset("dll_3.c", 40, dll, "struct dll", "*dll", & dll->head, "struct node *",
                  "dll->head", dll->head, "struct node", "(struct node *)((void *)0)",
                  0);
  dll->tail = (struct node *)((void *)0);
  logAssignOffset("dll_3.c", 41, dll, "struct dll", "*dll", & dll->tail, "struct node *",
                  "dll->tail", dll->tail, "struct node", "(struct node *)((void *)0)",
                  0);
  logBlockExit("dll_3.c", 41);
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (dll);
  }
  }
}
}
struct node *node_malloc(int item ) 
{ 
  struct node *node ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "node", "struct node *", & node);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("dll_3.c", 47);
  tmp = malloc(sizeof(struct node ));
  logAssignNoOffset("dll_3.c", 47, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(struct node )", sizeof(struct node ));
  node = (struct node *)tmp;
  logAssignNoOffset("dll_3.c", 47, & node, "struct node *", "node", node, "struct node",
                    "(struct node *)tmp", 0);
  logBlockExit("dll_3.c", 47);
  if ((unsigned long )node == (unsigned long )((struct node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("dll_3.c", 49);
  node->next = (struct node *)0;
  logAssignOffset("dll_3.c", 49, node, "struct node", "*node", & node->next, "struct node *",
                  "node->next", node->next, "struct node", "(struct node *)0", 0);
  node->prev = (struct node *)0;
  logAssignOffset("dll_3.c", 50, node, "struct node", "*node", & node->prev, "struct node *",
                  "node->prev", node->prev, "struct node", "(struct node *)0", 0);
  node->item = item;
  logBlockExit("dll_3.c", 51);
  {
  logVarOutOfScope("node", & node);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (node);
  }
  }
}
}
int main(void) 
{ 
  struct dll *dll ;
  struct dll *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "dll", "struct dll *", & dll);
  logVarInScope("local", "tmp", "struct dll *", & tmp);
  tmp = create();
  logBlockEntry("dll_3.c", 59);
  logAssignNoOffset("dll_3.c", 59, & tmp, "struct dll *", "tmp", tmp, "struct dll",
                    "create", 0);
  dumpVarsOutOfScope();
  dll = tmp;
  logAssignNoOffset("dll_3.c", 59, & dll, "struct dll *", "dll", dll, "struct dll",
                    "tmp", 0);
  logBlockExit("dll_3.c", 61);
  insertHead(dll, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_3.c", 62);
  insertHead(dll, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_3.c", 63);
  insertHead(dll, 3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_3.c", 64);
  insertHead(dll, 4);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("dll_3.c", 65);
  insertHead(dll, 5);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("dll", & dll);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
