/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct node {
   struct node *next ;
   int value ;
};
typedef struct node node;
struct list {
   struct node *head ;
};
typedef struct list list;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
list *list_create(void) ;
void list_add(list *l , int item ) ;
int list_remove(list *l ) ;
void list_dispose(list *l ) ;
void list_add(list *l , int item ) 
{ 
  node *new ;
  void *tmp ;
  node *n ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "list *", & l);
  logVarInScope("local", "new", "node *", & new);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "n", "node *", & n);
  logBlockEntry("sll_1.c", 22);
  tmp = malloc(sizeof(node ));
  logAssignNoOffset("sll_1.c", 22, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(node )", sizeof(node ));
  new = (node *)tmp;
  logAssignNoOffset("sll_1.c", 22, & new, "struct node *", "new", new, "struct node",
                    "(node *)tmp", 0);
  logBlockExit("sll_1.c", 22);
  if ((unsigned long )new == (unsigned long )((node *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_1.c", 24);
  new->next = (struct node *)0;
  logAssignOffset("sll_1.c", 24, new, "struct node", "*new", & new->next, "struct node *",
                  "new->next", new->next, "struct node", "(struct node *)0", 0);
  new->value = item;
  n = l->head;
  logAssignNoOffset("sll_1.c", 27, & n, "struct node *", "n", n, "struct node", "l->head",
                    0);
  logBlockExit("sll_1.c", 27);
  if ((unsigned long )n == (unsigned long )((node *)0)) {
    logBlockEntry("sll_1.c", 29);
    l->head = new;
    logAssignOffset("sll_1.c", 29, l, "struct list", "*l", & l->head, "struct node *",
                    "l->head", l->head, "struct node", "new", 0);
    logBlockExit("sll_1.c", 29);
  } else {
    while ((unsigned long )n->next != (unsigned long )((struct node *)0)) {
      logComment("Loop-iteration-start_sll_1.c_31");
      {
      logBlockEntry("sll_1.c", 33);
      n = n->next;
      logAssignNoOffset("sll_1.c", 33, & n, "struct node *", "n", n, "struct node",
                        "n->next", 0);
      logBlockExit("sll_1.c", 33);
      }
      logComment("Loop-iteration-end");
    }
    logBlockEntry("sll_1.c", 35);
    n->next = new;
    logAssignOffset("sll_1.c", 35, n, "struct node", "*n", & n->next, "struct node *",
                    "n->next", n->next, "struct node", "new", 0);
    logBlockExit("sll_1.c", 35);
  }
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("new", & new);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("n", & n);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
list *list_create(void) 
{ 
  list *l ;
  void *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "list *", & l);
  logVarInScope("local", "tmp", "void *", & tmp);
  logBlockEntry("sll_1.c", 41);
  tmp = malloc(sizeof(list ));
  logAssignNoOffset("sll_1.c", 41, & tmp, "void *", "tmp", tmp, "void", "malloc",
                    1);
  logMallocInfo("sizeof(list )", sizeof(list ));
  l = (list *)tmp;
  logAssignNoOffset("sll_1.c", 41, & l, "struct list *", "l", l, "struct list", "(list *)tmp",
                    0);
  logBlockExit("sll_1.c", 41);
  if ((unsigned long )l == (unsigned long )((list *)0)) {
    abort();
    logBlockEntry("", -1);
    dumpVarsOutOfScope();
    logBlockExit("", -1);
  }
  logBlockEntry("sll_1.c", 43);
  l->head = (struct node *)0;
  logAssignOffset("sll_1.c", 43, l, "struct list", "*l", & l->head, "struct node *",
                  "l->head", l->head, "struct node", "(struct node *)0", 0);
  logBlockExit("sll_1.c", 43);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (l);
  }
  }
}
}
void list_dispose(list *l ) 
{ 
  node *current ;
  node *oldcurrent ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "list *", & l);
  logVarInScope("local", "current", "node *", & current);
  logVarInScope("local", "oldcurrent", "node *", & oldcurrent);
  logBlockEntry("sll_1.c", 49);
  current = l->head;
  logAssignNoOffset("sll_1.c", 49, & current, "struct node *", "current", current,
                    "struct node", "l->head", 0);
  logBlockExit("sll_1.c", 49);
  while ((unsigned long )current != (unsigned long )((node *)0)) {
    logComment("Loop-iteration-start_sll_1.c_50");
    {
    logBlockEntry("sll_1.c", 52);
    oldcurrent = current;
    logAssignNoOffset("sll_1.c", 52, & oldcurrent, "struct node *", "oldcurrent",
                      oldcurrent, "struct node", "current", 0);
    current = current->next;
    logAssignNoOffset("sll_1.c", 53, & current, "struct node *", "current", current,
                      "struct node", "current->next", 0);
    logFree("sll_1.c", 54, "(void *)oldcurrent", (void *)oldcurrent);
    free((void *)oldcurrent);
    logBlockExit("sll_1.c", 54);
    }
    logComment("Loop-iteration-end");
  }
  logBlockEntry("", -1);
  logFree("sll_1.c", 56, "(void *)l", (void *)l);
  free((void *)l);
  logBlockExit("sll_1.c", 56);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("current", & current);
  logVarOutOfScope("oldcurrent", & oldcurrent);
  {
  logComment("Function Exited");
  return;
  }
  }
}
}
int list_remove(list *l ) 
{ 
  node *n ;
  int i ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "l", "list *", & l);
  logVarInScope("local", "n", "node *", & n);
  logBlockEntry("sll_1.c", 62);
  n = l->head;
  logAssignNoOffset("sll_1.c", 62, & n, "struct node *", "n", n, "struct node", "l->head",
                    0);
  i = n->value;
  l->head = n->next;
  logAssignOffset("sll_1.c", 64, l, "struct list", "*l", & l->head, "struct node *",
                  "l->head", l->head, "struct node", "n->next", 0);
  logFree("sll_1.c", 65, "(void *)n", (void *)n);
  free((void *)n);
  logBlockExit("sll_1.c", 65);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("n", & n);
  {
  logComment("Function Exited");
  return (i);
  }
  }
}
}
int main(void) 
{ 
  int i ;
  list *l ;
  list *tmp ;

  {
  logComment("Function Entered");
  logVarInScope("local", "l", "list *", & l);
  logVarInScope("local", "tmp", "list *", & tmp);
  tmp = list_create();
  logBlockEntry("sll_1.c", 74);
  logAssignNoOffset("sll_1.c", 74, & tmp, "struct list *", "tmp", tmp, "struct list",
                    "list_create", 0);
  dumpVarsOutOfScope();
  l = tmp;
  logAssignNoOffset("sll_1.c", 74, & l, "struct list *", "l", l, "struct list", "tmp",
                    0);
  logBlockExit("sll_1.c", 75);
  list_add(l, 1);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_1.c", 76);
  list_add(l, 2);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_1.c", 77);
  list_add(l, 3);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_1.c", 78);
  i = list_remove(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("sll_1.c", 79);
  list_dispose(l);
  logBlockEntry("", -1);
  dumpVarsOutOfScope();
  logBlockExit("", -1);
  {
  logVarOutOfScope("l", & l);
  logVarOutOfScope("tmp", & tmp);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
