/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct _child {
   struct _child *next ;
};
typedef struct _child child_sll;
struct _parent {
   struct _parent *next ;
   child_sll first_sll_child ;
   child_sll second_sll_child ;
};
typedef struct _parent parent_sll;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int const   NUM_OPS_WEISS_STACK  ;
int const   INSERT_PROB_WEISS_STACK  ;
int const   DELETE_PROB_WEISS_STACK  ;
int const   NUM_OPS_GALILEO_QUEUE  ;
int const   INSERT_PROB_GALILEO_QUEUE  ;
int const   DELETE_PROB_GALILEO_QUEUE  ;
int const   OPID_SLL_INSERT  ;
int const   OPID_SLL_REMOVE  ;
int const   OPID_DLL_INSERT  ;
int const   OPID_DLL_REMOVE  ;
int const   OPID_SLL_INSERT_FRONT  ;
int const   OPID_SLL_INSERT_MIDDLE  ;
int const   OPID_SLL_INSERT_BACK  ;
int const   OPID_SLL_INSERT_FRONT_DH  ;
int const   OPID_SLL_REMOVE_FRONT  ;
int const   OPID_SLL_REMOVE_MIDDLE  ;
int const   OPID_SLL_REMOVE_BACK  ;
int const   OPID_SLL_REMOVE_FRONT_DH  ;
int const   OPID_DLL_INSERT_FRONT  ;
int const   OPID_DLL_INSERT_MIDDLE  ;
int const   OPID_DLL_INSERT_BACK  ;
int const   OPID_DLL_INSERT_FRONT_DH  ;
int const   OPID_DLL_REMOVE_FRONT  ;
int const   OPID_DLL_REMOVE_MIDDLE  ;
int const   OPID_DLL_REMOVE_BACK  ;
int const   OPID_DLL_REMOVE_FRONT_DH  ;
int const   OPID_BTREE_INSERT  ;
int const   OPID_BTREE_REMOVE  ;
char const   *operationLocationStrings[5]  ;
int main(int argc , char **argv ) 
{ 
  int parent_len ;
  int child_len ;
  int i ;
  int e ;
  parent_sll *head ;
  parent_sll *iter ;
  child_sll *child_iter ;
  void *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;
  parent_sll *parent_tmp ;
  child_sll *tmp___3 ;
  child_sll *tmp___4 ;

  {
  logComment("Function Entered");
  logVarInScope("formal", "argv", "char **", & argv);
  logVarInScope("local", "head", "parent_sll *", & head);
  logVarInScope("local", "iter", "parent_sll *", & iter);
  logVarInScope("local", "child_iter", "child_sll *", & child_iter);
  logVarInScope("local", "tmp", "void *", & tmp);
  logVarInScope("local", "tmp___0", "void *", & tmp___0);
  logVarInScope("local", "tmp___1", "void *", & tmp___1);
  logVarInScope("local", "tmp___2", "void *", & tmp___2);
  logVarInScope("local", "parent_tmp", "parent_sll *", & parent_tmp);
  logVarInScope("local", "tmp___3", "child_sll *", & tmp___3);
  logVarInScope("local", "tmp___4", "child_sll *", & tmp___4);
  logBlockEntry("sll-with-two-slls.c", 18);
  parent_len = 10;
  child_len = 5;
  tmp = malloc(sizeof(parent_sll ));
  logAssignNoOffset("sll-with-two-slls.c", 26, & tmp, "void *", "tmp", tmp, "void",
                    "malloc", 1);
  logMallocInfo("sizeof(parent_sll )", sizeof(parent_sll ));
  head = (parent_sll *)tmp;
  logAssignNoOffset("sll-with-two-slls.c", 26, & head, "struct _parent *", "head",
                    head, "struct _parent", "(parent_sll *)tmp", 0);
  iter = head;
  logAssignNoOffset("sll-with-two-slls.c", 27, & iter, "struct _parent *", "iter",
                    iter, "struct _parent", "head", 0);
  i = 0;
  logBlockExit("sll-with-two-slls.c", 29);
  while (i < parent_len) {
    logComment("Loop-iteration-start_sll-with-two-slls.c_29");
    {
    logBlockEntry("sll-with-two-slls.c", 31);
    child_iter = & iter->first_sll_child;
    logAssignNoOffset("sll-with-two-slls.c", 31, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "& iter->first_sll_child",
                      0);
    e = 0;
    logBlockExit("sll-with-two-slls.c", 32);
    while (1) {
      if (! (e < child_len)) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      logBlockEntry("sll-with-two-slls.c", 33);
      tmp___0 = malloc(sizeof(child_sll ));
      logAssignNoOffset("sll-with-two-slls.c", 33, & tmp___0, "void *", "tmp___0",
                        tmp___0, "void", "malloc", 1);
      logMallocInfo("sizeof(child_sll )", sizeof(child_sll ));
      child_iter->next = (struct _child *)tmp___0;
      logAssignOffset("sll-with-two-slls.c", 33, child_iter, "struct _child", "*child_iter",
                      & child_iter->next, "struct _child *", "child_iter->next", child_iter->next,
                      "struct _child", "(struct _child *)tmp___0", 0);
      child_iter = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 34, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "child_iter->next",
                        0);
      child_iter->next = (struct _child *)((void *)0);
      logAssignOffset("sll-with-two-slls.c", 35, child_iter, "struct _child", "*child_iter",
                      & child_iter->next, "struct _child *", "child_iter->next", child_iter->next,
                      "struct _child", "(struct _child *)((void *)0)", 0);
      e ++;
      logBlockExit("sll-with-two-slls.c", 32);
    }
    logBlockEntry("sll-with-two-slls.c", 38);
    child_iter = & iter->second_sll_child;
    logAssignNoOffset("sll-with-two-slls.c", 38, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "& iter->second_sll_child",
                      0);
    e = 0;
    logBlockExit("sll-with-two-slls.c", 39);
    while (1) {
      if (! (e < child_len)) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      logBlockEntry("sll-with-two-slls.c", 40);
      tmp___1 = malloc(sizeof(child_sll ));
      logAssignNoOffset("sll-with-two-slls.c", 40, & tmp___1, "void *", "tmp___1",
                        tmp___1, "void", "malloc", 1);
      logMallocInfo("sizeof(child_sll )", sizeof(child_sll ));
      child_iter->next = (struct _child *)tmp___1;
      logAssignOffset("sll-with-two-slls.c", 40, child_iter, "struct _child", "*child_iter",
                      & child_iter->next, "struct _child *", "child_iter->next", child_iter->next,
                      "struct _child", "(struct _child *)tmp___1", 0);
      child_iter = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 41, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "child_iter->next",
                        0);
      child_iter->next = (struct _child *)((void *)0);
      logAssignOffset("sll-with-two-slls.c", 42, child_iter, "struct _child", "*child_iter",
                      & child_iter->next, "struct _child *", "child_iter->next", child_iter->next,
                      "struct _child", "(struct _child *)((void *)0)", 0);
      e ++;
      logBlockExit("sll-with-two-slls.c", 39);
    }
    logBlockEntry("sll-with-two-slls.c", 45);
    tmp___2 = malloc(sizeof(parent_sll ));
    logAssignNoOffset("sll-with-two-slls.c", 45, & tmp___2, "void *", "tmp___2", tmp___2,
                      "void", "malloc", 1);
    logMallocInfo("sizeof(parent_sll )", sizeof(parent_sll ));
    iter->next = (struct _parent *)tmp___2;
    logAssignOffset("sll-with-two-slls.c", 45, iter, "struct _parent", "*iter", & iter->next,
                    "struct _parent *", "iter->next", iter->next, "struct _parent",
                    "(struct _parent *)tmp___2", 0);
    iter = iter->next;
    logAssignNoOffset("sll-with-two-slls.c", 46, & iter, "struct _parent *", "iter",
                      iter, "struct _parent", "iter->next", 0);
    iter->next = (struct _parent *)((void *)0);
    logAssignOffset("sll-with-two-slls.c", 47, iter, "struct _parent", "*iter", & iter->next,
                    "struct _parent *", "iter->next", iter->next, "struct _parent",
                    "(struct _parent *)((void *)0)", 0);
    iter->first_sll_child.next = (struct _child *)((void *)0);
    logAssignOffset("sll-with-two-slls.c", 48, iter, "struct _parent", "*iter", & iter->first_sll_child.next,
                    "struct _child *", "iter->first_sll_child.next", iter->first_sll_child.next,
                    "struct _child", "(struct _child *)((void *)0)", 0);
    iter->second_sll_child.next = (struct _child *)((void *)0);
    logAssignOffset("sll-with-two-slls.c", 49, iter, "struct _parent", "*iter", & iter->second_sll_child.next,
                    "struct _child *", "iter->second_sll_child.next", iter->second_sll_child.next,
                    "struct _child", "(struct _child *)((void *)0)", 0);
    i ++;
    logBlockExit("sll-with-two-slls.c", 29);
    }
    logComment("Loop-iteration-end");
  }
  printf((char const   * __restrict  )"Lists created\n");
  printf((char const   * __restrict  )"Print lists\n");
  logBlockEntry("sll-with-two-slls.c", 55);
  iter = head;
  logAssignNoOffset("sll-with-two-slls.c", 55, & iter, "struct _parent *", "iter",
                    iter, "struct _parent", "head", 0);
  logBlockExit("sll-with-two-slls.c", 55);
  while (iter) {
    logComment("Loop-iteration-start_sll-with-two-slls.c_56");
    {
    printf((char const   * __restrict  )"Visiting parent: %p\n", iter);
    logBlockEntry("sll-with-two-slls.c", 58);
    child_iter = & iter->first_sll_child;
    logAssignNoOffset("sll-with-two-slls.c", 58, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "& iter->first_sll_child",
                      0);
    logBlockExit("sll-with-two-slls.c", 58);
    while (1) {
      if (! child_iter) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      printf((char const   * __restrict  )"\tVisiting first child: %p\n", child_iter);
      logBlockEntry("sll-with-two-slls.c", 61);
      child_iter = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 61, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "child_iter->next",
                        0);
      logBlockExit("sll-with-two-slls.c", 61);
    }
    logBlockEntry("sll-with-two-slls.c", 63);
    child_iter = & iter->second_sll_child;
    logAssignNoOffset("sll-with-two-slls.c", 63, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "& iter->second_sll_child",
                      0);
    logBlockExit("sll-with-two-slls.c", 63);
    while (1) {
      if (! child_iter) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      printf((char const   * __restrict  )"\tVisiting second child: %p\n", child_iter);
      logBlockEntry("sll-with-two-slls.c", 66);
      child_iter = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 66, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "child_iter->next",
                        0);
      logBlockExit("sll-with-two-slls.c", 66);
    }
    logBlockEntry("sll-with-two-slls.c", 68);
    iter = iter->next;
    logAssignNoOffset("sll-with-two-slls.c", 68, & iter, "struct _parent *", "iter",
                      iter, "struct _parent", "iter->next", 0);
    logBlockExit("sll-with-two-slls.c", 68);
    }
    logComment("Loop-iteration-end");
  }
  printf((char const   * __restrict  )"Lists printed\n");
  printf((char const   * __restrict  )"Destroy lists\n");
  logBlockEntry("sll-with-two-slls.c", 74);
  iter = head;
  logAssignNoOffset("sll-with-two-slls.c", 74, & iter, "struct _parent *", "iter",
                    iter, "struct _parent", "head", 0);
  logBlockExit("sll-with-two-slls.c", 74);
  while (iter) {
    logComment("Loop-iteration-start_sll-with-two-slls.c_75");
    {
    logBlockEntry("sll-with-two-slls.c", 76);
    parent_tmp = iter->next;
    logAssignNoOffset("sll-with-two-slls.c", 76, & parent_tmp, "struct _parent *",
                      "parent_tmp", parent_tmp, "struct _parent", "iter->next", 0);
    logBlockExit("sll-with-two-slls.c", 77);
    printf((char const   * __restrict  )"Visiting parent: %p\n", iter);
    logBlockEntry("sll-with-two-slls.c", 78);
    child_iter = iter->first_sll_child.next;
    logAssignNoOffset("sll-with-two-slls.c", 78, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "iter->first_sll_child.next",
                      0);
    logBlockExit("sll-with-two-slls.c", 78);
    while (1) {
      if (! child_iter) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      logBlockEntry("sll-with-two-slls.c", 80);
      tmp___3 = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 80, & tmp___3, "struct _child *", "tmp___3",
                        tmp___3, "struct _child", "child_iter->next", 0);
      logBlockExit("sll-with-two-slls.c", 81);
      printf((char const   * __restrict  )"\tFreeing first child: %p\n", child_iter);
      logBlockEntry("", -1);
      logFree("sll-with-two-slls.c", 82, "(void *)child_iter", (void *)child_iter);
      free((void *)child_iter);
      child_iter = tmp___3;
      logAssignNoOffset("sll-with-two-slls.c", 83, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "tmp___3", 0);
      logBlockExit("sll-with-two-slls.c", 83);
    }
    logBlockEntry("sll-with-two-slls.c", 85);
    child_iter = iter->second_sll_child.next;
    logAssignNoOffset("sll-with-two-slls.c", 85, & child_iter, "struct _child *",
                      "child_iter", child_iter, "struct _child", "iter->second_sll_child.next",
                      0);
    logBlockExit("sll-with-two-slls.c", 85);
    while (1) {
      if (! child_iter) {
        {
        logComment("Loop-iteration-end");
        break;
        }
      }
      logBlockEntry("sll-with-two-slls.c", 87);
      tmp___4 = child_iter->next;
      logAssignNoOffset("sll-with-two-slls.c", 87, & tmp___4, "struct _child *", "tmp___4",
                        tmp___4, "struct _child", "child_iter->next", 0);
      logBlockExit("sll-with-two-slls.c", 88);
      printf((char const   * __restrict  )"\tFreeing second child: %p\n", child_iter);
      logBlockEntry("", -1);
      logFree("sll-with-two-slls.c", 89, "(void *)child_iter", (void *)child_iter);
      free((void *)child_iter);
      child_iter = tmp___4;
      logAssignNoOffset("sll-with-two-slls.c", 90, & child_iter, "struct _child *",
                        "child_iter", child_iter, "struct _child", "tmp___4", 0);
      logBlockExit("sll-with-two-slls.c", 90);
    }
    logBlockEntry("", -1);
    logFree("sll-with-two-slls.c", 92, "(void *)iter", (void *)iter);
    free((void *)iter);
    iter = parent_tmp;
    logAssignNoOffset("sll-with-two-slls.c", 93, & iter, "struct _parent *", "iter",
                      iter, "struct _parent", "parent_tmp", 0);
    logBlockExit("sll-with-two-slls.c", 93);
    }
    logComment("Loop-iteration-end");
  }
  {
  logVarOutOfScope("argv", & argv);
  logVarOutOfScope("head", & head);
  logVarOutOfScope("iter", & iter);
  logVarOutOfScope("child_iter", & child_iter);
  logVarOutOfScope("tmp", & tmp);
  logVarOutOfScope("tmp___0", & tmp___0);
  logVarOutOfScope("tmp___1", & tmp___1);
  logVarOutOfScope("tmp___2", & tmp___2);
  logVarOutOfScope("parent_tmp", & parent_tmp);
  logVarOutOfScope("tmp___3", & tmp___3);
  logVarOutOfScope("tmp___4", & tmp___4);
  {
  logComment("Function Exited");
  return (0);
  }
  }
}
}
